import type { AnimalHabitat, AnimalKind, AnimalRecord } from "./schema";

type Seed = {
  slug: string;
  common: string;
  latin: string;
  kind: AnimalKind;
  habitat: AnimalHabitat;
  range: string;
  region: string;
  diet: string;
  connected: string;
  fact: string;
  safety?: string;
  conservation?: string;
  names?: string[];
};

const SEEDS: Seed[] = [
  // Fish — ocean, reef, river
  { slug: "clownfish", common: "Clownfish", latin: "Amphiprion ocellaris", kind: "fish", habitat: "reef", range: "Coral reefs of the Indian and Pacific Oceans", region: "southeast-asia", diet: "Tiny reef snacks and algae", connected: "Lives with a sea anemone. The reef is a garden in the sea.", fact: "Clownfish can change jobs in their family if they need to." },
  { slug: "atlantic-salmon", common: "Atlantic salmon", latin: "Salmo salar", kind: "fish", habitat: "river", range: "North Atlantic rivers and sea", region: "britain", diet: "Insects when small, then fish at sea", connected: "Born in a river, grows in the ocean, comes home. Forests keep the river cool.", fact: "Some salmon swim hundreds of kilometres to spawn." },
  { slug: "pacific-salmon", common: "Pacific salmon", latin: "Oncorhynchus spp.", kind: "fish", habitat: "river", range: "North Pacific", region: "east-asia", diet: "Plankton then fish", connected: "After they spawn, their bodies feed the forest. Bears, trees and rivers share them.", fact: "There are several Pacific salmon kinds, not just one." },
  { slug: "cod", common: "Atlantic cod", latin: "Gadus morhua", kind: "fish", habitat: "ocean", range: "North Atlantic", region: "britain", diet: "Smaller fish and crabs", connected: "People have fished cod for centuries. The sea needs rest too.", fact: "Cod can live many years if they are not overfished." },
  { slug: "tuna", common: "Atlantic bluefin tuna", latin: "Thunnus thynnus", kind: "fish", habitat: "ocean", range: "Atlantic Ocean", region: "mediterranean", diet: "Fish and squid", connected: "A fast ocean traveller. What we eat from the sea must be shared with the future.", fact: "Bluefin can warm their bodies so they can swim in cooler water." },
  { slug: "yellowfin-tuna", common: "Yellowfin tuna", latin: "Thunnus albacares", kind: "fish", habitat: "ocean", range: "Warm oceans worldwide", region: "pacific", diet: "Fish and squid", connected: "Open-ocean fish need a healthy plankton sea.", fact: "The yellow fin is a clue in the name." },
  { slug: "sardine", common: "Sardine", latin: "Sardina pilchardus", kind: "fish", habitat: "ocean", range: "Northeast Atlantic and Mediterranean", region: "mediterranean", diet: "Plankton", connected: "Tiny fish feed bigger fish, birds and people.", fact: "Sardines swim in huge shining schools." },
  { slug: "anchovy", common: "Anchovy", latin: "Engraulis encrasicolus", kind: "fish", habitat: "ocean", range: "Atlantic and Mediterranean", region: "mediterranean", diet: "Plankton", connected: "A small fish with a big job in the food web.", fact: "Many sea birds wait for anchovy schools." },
  { slug: "herring", common: "Atlantic herring", latin: "Clupea harengus", kind: "fish", habitat: "ocean", range: "North Atlantic", region: "britain", diet: "Plankton", connected: "Herring schools are moving silver forests of the sea.", fact: "One school can hold millions of fish." },
  { slug: "mackerel", common: "Atlantic mackerel", latin: "Scomber scombrus", kind: "fish", habitat: "ocean", range: "North Atlantic", region: "britain", diet: "Small fish and plankton", connected: "Fast swimmers that follow cool, food-rich water.", fact: "Stripes help them hide in moving light." },
  { slug: "haddock", common: "Haddock", latin: "Melanogrammus aeglefinus", kind: "fish", habitat: "ocean", range: "North Atlantic", region: "britain", diet: "Worms and small sea animals", connected: "Lives near the seabed. The bottom of the sea is a home too.", fact: "A black spot on the side is a haddock clue." },
  { slug: "halibut", common: "Atlantic halibut", latin: "Hippoglossus hippoglossus", kind: "fish", habitat: "ocean", range: "North Atlantic", region: "britain", diet: "Fish and crabs", connected: "A flatfish that lies on the sand. Camouflage is a kind of hiding garden.", fact: "Both eyes sit on one side of the head." },
  { slug: "flounder", common: "Flounder", latin: "Platichthys flesus", kind: "fish", habitat: "ocean", range: "European coasts", region: "britain", diet: "Small animals on the sand", connected: "Flatfish show how a body can match its place.", fact: "They start with an eye on each side, then one moves." },
  { slug: "plaice", common: "Plaice", latin: "Pleuronectes platessa", kind: "fish", habitat: "ocean", range: "Northeast Atlantic", region: "britain", diet: "Shellfish and worms", connected: "Orange spots on a sandy fish — a map on the skin.", fact: "Plaice rest on the seabed by day." },
  { slug: "swordfish", common: "Swordfish", latin: "Xiphias gladius", kind: "fish", habitat: "ocean", range: "Warm and temperate oceans", region: "pacific", diet: "Fish and squid", connected: "The ‘sword’ is a tool for hunting in the open sea, not a toy.", fact: "They can heat their eyes to see better in the deep." },
  { slug: "marlin", common: "Blue marlin", latin: "Makaira nigricans", kind: "fish", habitat: "ocean", range: "Warm oceans", region: "caribbean", diet: "Fish and squid", connected: "Open-water hunters need plenty of smaller fish.", fact: "The long bill is used to slash, then catch." },
  { slug: "great-white-shark", common: "Great white shark", latin: "Carcharodon carcharias", kind: "fish", habitat: "ocean", range: "Coastal oceans worldwide", region: "australia", diet: "Fish and marine mammals", connected: "Sharks are not villains. They keep ocean numbers in balance.", fact: "Most sharks do not bother people. We are not their food.", safety: "Never swim toward a wild shark. Watch from a safe place with an adult.", conservation: "Needs careful protection in many waters" },
  { slug: "whale-shark", common: "Whale shark", latin: "Rhincodon typus", kind: "fish", habitat: "ocean", range: "Warm oceans", region: "pacific", diet: "Plankton", connected: "The biggest fish eats the smallest food — drifting plankton.", fact: "A whale shark is a fish, not a whale." },
  { slug: "manta-ray", common: "Oceanic manta ray", latin: "Mobula birostris", kind: "fish", habitat: "ocean", range: "Warm oceans", region: "pacific", diet: "Plankton", connected: "Wings in the water filter tiny food, like a flying sieve.", fact: "Mantas often visit cleaning stations on reefs." },
  { slug: "stingray", common: "Southern stingray", latin: "Hypanus americanus", kind: "fish", habitat: "ocean", range: "Western Atlantic and Caribbean", region: "caribbean", diet: "Shellfish in the sand", connected: "They hide under sand. Shuffle feet in shallows with an adult.", fact: "The barb is for defence, not hunting people.", safety: "Do not step on a ray. Shuffle and look with an adult." },
  { slug: "seahorse", common: "Seahorse", latin: "Hippocampus kuda", kind: "fish", habitat: "reef", range: "Warm coastal seas", region: "southeast-asia", diet: "Tiny drifting animals", connected: "Holds onto sea grass. If the grass goes, the seahorse loses its home.", fact: "The father seahorse carries the eggs." },
  { slug: "parrotfish", common: "Parrotfish", latin: "Scarus spp.", kind: "fish", habitat: "reef", range: "Tropical reefs", region: "caribbean", diet: "Algae on coral rock", connected: "They nibble algae so coral can breathe. Beach sand is partly parrotfish poop — a true garden fact.", fact: "A beak-like mouth scrapes the reef like a parrot’s beak." },
  { slug: "angelfish", common: "Queen angelfish", latin: "Holacanthus ciliaris", kind: "fish", habitat: "reef", range: "Western Atlantic reefs", region: "caribbean", diet: "Sponges and algae", connected: "Bright reef fish need a living coral city.", fact: "Young and grown angelfish can look different." },
  { slug: "butterflyfish", common: "Butterflyfish", latin: "Chaetodon capistratus", kind: "fish", habitat: "reef", range: "Caribbean reefs", region: "caribbean", diet: "Coral polyps and small animals", connected: "A healthy reef is a cafeteria of colours.", fact: "A dark spot near the tail can confuse a hunter." },
  { slug: "grouper", common: "Nassau grouper", latin: "Epinephelus striatus", kind: "fish", habitat: "reef", range: "Caribbean", region: "caribbean", diet: "Fish and crabs", connected: "Big reef fish need quiet seasons to gather and spawn.", fact: "They can change colour when they meet.", conservation: "Needs protection when they gather to spawn" },
  { slug: "snapper", common: "Yellowtail snapper", latin: "Ocyurus chrysurus", kind: "fish", habitat: "reef", range: "Western Atlantic", region: "caribbean", diet: "Fish and shrimp", connected: "Reef edges are highways between coral and open water.", fact: "The yellow stripe is a name you can see." },
  { slug: "barracuda", common: "Great barracuda", latin: "Sphyraena barracuda", kind: "fish", habitat: "reef", range: "Warm oceans", region: "caribbean", diet: "Fish", connected: "A long hunter of the reef edge. Shiny things can confuse them.", fact: "They often hang still, then dart.", safety: "Do not wear bright shiny jewellery in their water." },
  { slug: "flying-fish", common: "Flying fish", latin: "Exocoetus volitans", kind: "fish", habitat: "ocean", range: "Warm oceans", region: "caribbean", diet: "Plankton", connected: "Wings of fin let them glide above waves to escape.", fact: "They do not truly fly like birds — they glide." },
  { slug: "moray-eel", common: "Green moray", latin: "Gymnothorax funebris", kind: "fish", habitat: "reef", range: "Western Atlantic", region: "caribbean", diet: "Fish and crabs", connected: "Lives in holes in the reef. A home in the rock.", fact: "The open mouth is how they breathe, not always a threat.", safety: "Never put a hand in a reef hole." },
  { slug: "pufferfish", common: "Porcupinefish", latin: "Diodon hystrix", kind: "fish", habitat: "reef", range: "Warm oceans", region: "pacific", diet: "Shellfish", connected: "Inflates when scared. Poison is not a snack.", fact: "Spines stand up when it puffs.", safety: "Do not eat wild pufferfish. Some are dangerous food unless an expert prepares them." },
  { slug: "lionfish", common: "Red lionfish", latin: "Pterois volitans", kind: "fish", habitat: "reef", range: "Native to Indo-Pacific; also in Atlantic", region: "southeast-asia", diet: "Small fish", connected: "Beautiful spines. In some seas they are visitors that eat too much.", fact: "Venom is in the spines, not the meat.", safety: "Do not touch the spines." },
  { slug: "tilapia", common: "Nile tilapia", latin: "Oreochromis niloticus", kind: "fish", habitat: "river", range: "Africa; farmed worldwide", region: "east-africa-fallback", diet: "Algae and plants", connected: "A farmed fish in many countries. Rivers and farms both grow food.", fact: "Parents can keep babies in their mouths to stay safe." },
  { slug: "carp", common: "Common carp", latin: "Cyprinus carpio", kind: "fish", habitat: "river", range: "Europe and Asia; now many lakes", region: "east-asia", diet: "Plants and small animals in mud", connected: "A pond fish people have kept for centuries.", fact: "Barbels by the mouth feel food in the mud." },
  { slug: "koi", common: "Koi", latin: "Cyprinus carpio (ornamental)", kind: "fish", habitat: "garden", range: "Bred in East Asia", region: "east-asia", diet: "Pond food", connected: "Garden ponds are tiny lakes we care for.", fact: "Colours were chosen by people over many years." },
  { slug: "goldfish", common: "Goldfish", latin: "Carassius auratus", kind: "fish", habitat: "garden", range: "East Asia, now home ponds", region: "east-asia", diet: "Flakes and plants", connected: "A cousin of wild carp. Bowls are too small — they need space and clean water.", fact: "They can remember more than a few seconds." },
  { slug: "catfish", common: "Channel catfish", latin: "Ictalurus punctatus", kind: "fish", habitat: "river", range: "North America", region: "north-america", diet: "Plants and small animals", connected: "Whiskers are feelers in cloudy water.", fact: "They can hear with their whole body in some ways." },
  { slug: "trout", common: "Brown trout", latin: "Salmo trutta", kind: "fish", habitat: "river", range: "Europe; moved to other cold rivers", region: "britain", diet: "Insects and small fish", connected: "Cold, clean rivers grow trout. Trees on the bank help.", fact: "Spots are like a map of the stream." },
  { slug: "rainbow-trout", common: "Rainbow trout", latin: "Oncorhynchus mykiss", kind: "fish", habitat: "river", range: "Pacific North America", region: "north-america", diet: "Insects", connected: "Needs cold oxygen-rich water.", fact: "The pink stripe is a clue." },
  { slug: "pike", common: "Northern pike", latin: "Esox lucius", kind: "fish", habitat: "wetland", range: "Northern fresh waters", region: "britain", diet: "Fish", connected: "A waiting hunter in the reeds.", fact: "They lie still like a stick, then rush." },
  { slug: "perch", common: "European perch", latin: "Perca fluviatilis", kind: "fish", habitat: "river", range: "Europe", region: "britain", diet: "Insects and small fish", connected: "Stripes hide them in weed.", fact: "Young perch stay in schools." },
  { slug: "bass-fish", common: "Largemouth bass", latin: "Micropterus nigricans", kind: "fish", habitat: "river", range: "North America", region: "north-america", diet: "Fish and frogs", connected: "Lakes with plants give baby fish hiding places.", fact: "The big mouth is in the name." },
  { slug: "piranha", common: "Red-bellied piranha", latin: "Pygocentrus nattereri", kind: "fish", habitat: "river", range: "Amazon basin", region: "amazon", diet: "Fish and fruit that falls in", connected: "They are not movie monsters. Many eat fruit from the flooded forest.", fact: "Flooded forest time means fruit for fish.", safety: "Wild rivers are not swimming pools. Go only with a trusted adult." },
  { slug: "arowana", common: "Silver arowana", latin: "Osteoglossum bicirrhosum", kind: "fish", habitat: "river", range: "Amazon", region: "amazon", diet: "Insects and small animals at the surface", connected: "Jumps for food from the air above the river.", fact: "Two barbels on the chin feel the surface." },
  { slug: "electric-eel", common: "Electric eel", latin: "Electrophorus electricus", kind: "fish", habitat: "river", range: "Amazon", region: "amazon", diet: "Fish", connected: "Makes electricity in its body — living science, not a cartoon zap.", fact: "It is a knifefish, not a true eel.", safety: "Never touch one." },
  { slug: "lungfish", common: "African lungfish", latin: "Protopterus annectens", kind: "fish", habitat: "wetland", range: "Africa", region: "west-africa", diet: "Small animals", connected: "Can breathe air when the pool dries. Water and land are cousins.", fact: "It can wait in mud until rain returns." },
  { slug: "coelacanth", common: "Coelacanth", latin: "Latimeria chalumnae", kind: "fish", habitat: "ocean", range: "Western Indian Ocean deep reefs", region: "southern-africa", diet: "Fish and squid", connected: "A very old kind of fish. The ocean keeps deep stories.", fact: "People once thought it lived only in fossils.", conservation: "Rare and protected" },
  { slug: "sturgeon", common: "European sturgeon", latin: "Acipenser sturio", kind: "fish", habitat: "river", range: "Europe (now very rare)", region: "britain", diet: "Small animals in mud", connected: "An ancient river traveller. Dams can block a fish’s road home.", fact: "Bony scutes run along the body.", conservation: "Critically needs our care" },
  { slug: "eel", common: "European eel", latin: "Anguilla anguilla", kind: "fish", habitat: "river", range: "Europe to Sargasso Sea", region: "britain", diet: "Small animals", connected: "Born in the far Atlantic, grows in our rivers, returns to spawn.", fact: "Nobody has filmed their full ocean spawning well yet.", conservation: "Needs protection" },
  { slug: "betta", common: "Betta / Siamese fighting fish", latin: "Betta splendens", kind: "fish", habitat: "wetland", range: "Southeast Asia", region: "southeast-asia", diet: "Insects", connected: "Wild bettas live in warm shallow water, not tiny vases.", fact: "The labyrinth organ lets them breathe air at the surface." },
  { slug: "guppy", common: "Guppy", latin: "Poecilia reticulata", kind: "fish", habitat: "river", range: "South America; now many streams", region: "amazon", diet: "Algae and tiny animals", connected: "A small fish that people study for colour and babies.", fact: "They have live babies, not eggs in a nest." },
  { slug: "flying-gurnard", common: "Flying gurnard", latin: "Dactylopterus volitans", kind: "fish", habitat: "ocean", range: "Atlantic warm coasts", region: "caribbean", diet: "Small animals on sand", connected: "Big colourful fins look like wings but it walks the sand.", fact: "They can ‘walk’ with feeler fins." },
  { slug: "wrasse", common: "Cleaner wrasse", latin: "Labroides dimidiatus", kind: "fish", habitat: "reef", range: "Indo-Pacific reefs", region: "pacific", diet: "Parasites off other fish", connected: "A little doctor of the reef. Other fish wait in line.", fact: "They set up cleaning stations." },
  { slug: "surgeonfish", common: "Blue tang", latin: "Paracanthurus hepatus", kind: "fish", habitat: "reef", range: "Indo-Pacific", region: "pacific", diet: "Algae", connected: "Grazes the reef like a lawnmower of the coral garden.", fact: "A spine by the tail is the ‘surgeon’ part.", safety: "Do not handle wild reef fish." },
  { slug: "triggerfish", common: "Picasso triggerfish", latin: "Rhinecanthus aculeatus", kind: "fish", habitat: "reef", range: "Indo-Pacific", region: "pacific", diet: "Shellfish and urchins", connected: "They crunch hard food and keep urchins in check.", fact: "A trigger spine can lock them in a hole." },

  // Other ocean life
  { slug: "blue-whale", common: "Blue whale", latin: "Balaenoptera musculus", kind: "mammal", habitat: "ocean", range: "All oceans", region: "pacific", diet: "Krill", connected: "The largest animal eats some of the smallest. Ocean plants start that chain.", fact: "A blue whale’s heart is about the size of a small car.", conservation: "Protected after hunting in the past" },
  { slug: "humpback-whale", common: "Humpback whale", latin: "Megaptera novaeangliae", kind: "mammal", habitat: "ocean", range: "All oceans", region: "pacific", diet: "Krill and small fish", connected: "Songs travel through water. The sea has music too.", fact: "Long pectoral fins look like wings." },
  { slug: "sperm-whale", common: "Sperm whale", latin: "Physeter macrocephalus", kind: "mammal", habitat: "ocean", range: "Deep oceans", region: "pacific", diet: "Squid", connected: "Dives into the dark to feed, then breathes at the bright surface.", fact: "The huge head holds a special oil used in diving." },
  { slug: "orca", common: "Orca / killer whale", latin: "Orcinus orca", kind: "mammal", habitat: "ocean", range: "All oceans", region: "pacific", diet: "Fish or mammals, depending on the family", connected: "Family pods share hunting skills. Each one teach one, even in the sea.", fact: "Different orca families eat different foods." },
  { slug: "bottlenose-dolphin", common: "Bottlenose dolphin", latin: "Tursiops truncatus", kind: "mammal", habitat: "ocean", range: "Warm and temperate coasts", region: "caribbean", diet: "Fish", connected: "Breathes air. A mammal in the sea, like us on land.", fact: "They click to ‘see’ with sound." },
  { slug: "manatee", common: "West Indian manatee", latin: "Trichechus manatus", kind: "mammal", habitat: "wetland", range: "Caribbean and nearby coasts", region: "caribbean", diet: "Sea grass", connected: "A grazing cow of the water. Sea grass meadows are underwater farms.", fact: "They come up for air.", conservation: "Needs slow boats and healthy grass" },
  { slug: "harbour-seal", common: "Harbour seal", latin: "Phoca vitulina", kind: "mammal", habitat: "ocean", range: "North coasts", region: "britain", diet: "Fish", connected: "Rests on rocks, hunts in the water. Two homes.", fact: "Pups can swim very young." },
  { slug: "sea-otter", common: "Sea otter", latin: "Enhydra lutris", kind: "mammal", habitat: "ocean", range: "North Pacific", region: "north-america", diet: "Urchins and shellfish", connected: "Otters eat urchins, so kelp forests can grow. A helper of the sea garden.", fact: "They use stones as tools on their tummies." },
  { slug: "walrus", common: "Walrus", latin: "Odobenus rosmarus", kind: "mammal", habitat: "polar", range: "Arctic", region: "arctic", diet: "Clams on the seafloor", connected: "Ice is a rest place. Polar homes need cold seas.", fact: "Tusks help them climb ice.", conservation: "Ice change is a worry" },
  { slug: "green-turtle", common: "Green sea turtle", latin: "Chelonia mydas", kind: "reptile", habitat: "ocean", range: "Warm oceans", region: "caribbean", diet: "Sea grass as adults", connected: "Nests on beaches. Lights and litter can confuse hatchlings.", fact: "They return to beaches near where they hatched.", conservation: "Protected in many places", safety: "Never pick up a hatchling. Let it walk to the sea." },
  { slug: "leatherback", common: "Leatherback turtle", latin: "Dermochelys coriacea", kind: "reptile", habitat: "ocean", range: "Open oceans", region: "caribbean", diet: "Jellyfish", connected: "Plastic bags can look like jellyfish. Keep plastic out of the sea.", fact: "The biggest sea turtle has a rubbery shell." },
  { slug: "octopus", common: "Common octopus", latin: "Octopus vulgaris", kind: "invertebrate", habitat: "reef", range: "Warm and temperate seas", region: "mediterranean", diet: "Crabs", connected: "Eight arms, a clever brain, a home in a den of shells.", fact: "They can change colour in a blink." },
  { slug: "squid", common: "Humboldt squid", latin: "Dosidicus gigas", kind: "invertebrate", habitat: "ocean", range: "Eastern Pacific", region: "pacific", diet: "Fish", connected: "A fast open-ocean hunter in the night water.", fact: "They glow and flash in groups." },
  { slug: "jellyfish", common: "Moon jellyfish", latin: "Aurelia aurita", kind: "invertebrate", habitat: "ocean", range: "Coasts worldwide", region: "worldwide", diet: "Tiny drifting animals", connected: "A body mostly of water. The sea itself made into an animal.", fact: "They pulse to move.", safety: "Some jellyfish sting. Do not touch. Tell an adult." },
  { slug: "starfish", common: "Ochre sea star", latin: "Pisaster ochraceus", kind: "invertebrate", habitat: "ocean", range: "Pacific North America", region: "north-america", diet: "Mussels", connected: "A key helper: eating mussels so seaweed and other lives can fit.", fact: "They can grow back an arm." },
  { slug: "coral", common: "Staghorn coral", latin: "Acropora cervicornis", kind: "invertebrate", habitat: "reef", range: "Caribbean", region: "caribbean", diet: "Tiny algae live inside them, plus drifting food", connected: "Coral is an animal that builds rock homes. Reefs are cities of the sea.", fact: "The colour often comes from tiny algae friends.", conservation: "Warm water can bleach coral" },
  { slug: "crab", common: "Caribbean land crab", latin: "Cardisoma guanhumi", kind: "invertebrate", habitat: "wetland", range: "Caribbean coasts", region: "caribbean", diet: "Leaves and fruit", connected: "Walks from land to sea to release babies. Two worlds, one life.", fact: "They breathe air but need damp gills." },
  { slug: "hermit-crab", common: "Hermit crab", latin: "Coenobita clypeatus", kind: "invertebrate", habitat: "garden", range: "Caribbean shores", region: "caribbean", diet: "Bits of plants and leftover food", connected: "Borrows shells. Empty shells are homes — do not take them all.", fact: "They change shells as they grow." },
  { slug: "lobster", common: "Caribbean spiny lobster", latin: "Panulirus argus", kind: "invertebrate", habitat: "reef", range: "Western Atlantic", region: "caribbean", diet: "Small animals", connected: "Hides in reef holes by day.", fact: "No big claws — long feelers instead." },
  { slug: "shrimp", common: "Cleaner shrimp", latin: "Lysmata amboinensis", kind: "invertebrate", habitat: "reef", range: "Indo-Pacific", region: "pacific", diet: "Bits on other animals’ skin", connected: "A tiny cleaner of the reef clinic.", fact: "Fish let them pick pests." },
  { slug: "oyster", common: "Eastern oyster", latin: "Crassostrea virginica", kind: "invertebrate", habitat: "wetland", range: "Atlantic Americas", region: "north-america", diet: "Filters tiny food from water", connected: "Oyster reefs clean water and shelter baby fish.", fact: "They glue themselves to rock and stay." },
  { slug: "mussel", common: "Blue mussel", latin: "Mytilus edulis", kind: "invertebrate", habitat: "ocean", range: "North Atlantic coasts", region: "britain", diet: "Filters water", connected: "Threads stick them to rocks in the tide.", fact: "The tide covers and uncovers their town twice a day." },

  // Insects and soil
  { slug: "honeybee", common: "Honeybee", latin: "Apis mellifera", kind: "insect", habitat: "garden", range: "Worldwide in gardens and wild", region: "mediterranean", diet: "Nectar and pollen", connected: "Moves pollen so fruit can grow. No bees, fewer apples, mangoes and tomatoes.", fact: "A dance in the hive tells where the flowers are." },
  { slug: "bumblebee", common: "Buff-tailed bumblebee", latin: "Bombus terrestris", kind: "insect", habitat: "garden", range: "Europe", region: "britain", diet: "Nectar and pollen", connected: "Fuzzy bees can pollinate in cool weather.", fact: "They buzz-pollinate some flowers." },
  { slug: "monarch", common: "Monarch butterfly", latin: "Danaus plexippus", kind: "insect", habitat: "sky", range: "Americas; some travel to Mexico", region: "mesoamerica", diet: "Milkweed as caterpillars", connected: "Needs milkweed. A garden plant is a passport for a journey.", fact: "Some fly thousands of kilometres." },
  { slug: "swallowtail", common: "Swallowtail butterfly", latin: "Papilio machaon", kind: "insect", habitat: "garden", range: "Europe and Asia", region: "britain", diet: "Nectar; caterpillars eat certain leaves", connected: "Caterpillar food plants matter as much as pretty flowers.", fact: "Tails on the wings look like a false head." },
  { slug: "ladybird", common: "Seven-spot ladybird", latin: "Coccinella septempunctata", kind: "insect", habitat: "garden", range: "Europe; now many gardens", region: "britain", diet: "Aphids", connected: "Eats the bugs that drink plant sap. A helper on the farm.", fact: "The spots are not always seven." },
  { slug: "ant", common: "Leafcutter ant", latin: "Atta cephalotes", kind: "insect", habitat: "forest", range: "Tropical Americas", region: "amazon", diet: "Fungus they grow on leaves", connected: "They farm fungus. Animals can be farmers too.", fact: "They carry leaf pieces like umbrellas." },
  { slug: "earthworm", common: "Earthworm", latin: "Lumbricus terrestris", kind: "invertebrate", habitat: "soil", range: "Soils in many temperate places", region: "britain", diet: "Dead leaves in soil", connected: "Grandma Soil’s helpers. Tunnels let rain and roots through.", fact: "They eat soil and leave richer soil behind." },
  { slug: "dragonfly", common: "Emperor dragonfly", latin: "Anax imperator", kind: "insect", habitat: "wetland", range: "Europe and Africa", region: "britain", diet: "Flying insects", connected: "Babies live in water, adults in air. Pond and sky are one story.", fact: "They can hover and dart." },
  { slug: "firefly", common: "Firefly", latin: "Photinus pyralis", kind: "insect", habitat: "garden", range: "North America", region: "north-america", diet: "As larvae, small soil animals", connected: "Light is a language. Dark nights let them talk.", fact: "The light is cold — it does not burn." },
  { slug: "cricket", common: "Field cricket", latin: "Gryllus campestris", kind: "insect", habitat: "garden", range: "Europe", region: "britain", diet: "Plants and tiny animals", connected: "Night songs from the grass.", fact: "They chirp by rubbing wings." },
  { slug: "grasshopper", common: "Meadow grasshopper", latin: "Chorthippus parallelus", kind: "insect", habitat: "garden", range: "Europe", region: "britain", diet: "Grass", connected: "A jumper of the meadow. Birds listen for them.", fact: "Big back legs store a spring." },
  { slug: "mosquito", common: "Mosquito", latin: "Culex pipiens", kind: "insect", habitat: "wetland", range: "Worldwide near still water", region: "worldwide", diet: "Nectar; some females also drink blood", connected: "Larvae live in still water. Empty pots help gardens stay kinder.", fact: "Only some kinds bite, and usually the females.", safety: "Use nets and cover skin where bites are a problem. Ask an adult." },
  { slug: "spider", common: "Garden spider", latin: "Araneus diadematus", kind: "invertebrate", habitat: "garden", range: "Europe", region: "britain", diet: "Insects in the web", connected: "Silk is a trap and a home. Spiders eat many garden insects.", fact: "The cross on the back is a clue.", safety: "Look, do not poke. Most garden spiders are not looking for you." },
  { slug: "snail", common: "Garden snail", latin: "Cornu aspersum", kind: "invertebrate", habitat: "garden", range: "Mediterranean origin; gardens worldwide", region: "mediterranean", diet: "Leaves", connected: "A slow gardener. Shells are homes they carry.", fact: "They make slime so they can slide." },

  // Birds
  { slug: "hummingbird", common: "Rufous hummingbird", latin: "Selasphorus rufus", kind: "bird", habitat: "garden", range: "Americas", region: "north-america", diet: "Nectar and tiny insects", connected: "Hovers like a bee. Flowers and birds share a deal: sip for a pollen ride.", fact: "Wings beat so fast they hum." },
  { slug: "sparrow", common: "House sparrow", latin: "Passer domesticus", kind: "bird", habitat: "farm", range: "Worldwide near people", region: "britain", diet: "Seeds and insects", connected: "A city and farm neighbour. Hedges give them homes.", fact: "They chirp in groups." },
  { slug: "robin", common: "European robin", latin: "Erithacus rubecula", kind: "bird", habitat: "garden", range: "Europe", region: "britain", diet: "Insects and worms", connected: "Follows the gardener because digging shows worms.", fact: "The red breast is a flag." },
  { slug: "eagle", common: "Bald eagle", latin: "Haliaeetus leucocephalus", kind: "bird", habitat: "sky", range: "North America", region: "north-america", diet: "Fish", connected: "A fisher of rivers. Clean water feeds the sky too.", fact: "They build huge stick nests." },
  { slug: "owl", common: "Barn owl", latin: "Tyto alba", kind: "bird", habitat: "farm", range: "Many countries", region: "britain", diet: "Mice", connected: "Night helper of the barn. Quiet wings.", fact: "A heart-shaped face funnels sound." },
  { slug: "parrot", common: "African grey parrot", latin: "Psittacus erithacus", kind: "bird", habitat: "forest", range: "West and Central Africa", region: "west-africa", diet: "Fruit, nuts and seeds", connected: "Forest fruit eaters plant trees when they drop seeds.", fact: "They can copy sounds, including words.", conservation: "Wild birds need their forests" },
  { slug: "macaw", common: "Scarlet macaw", latin: "Ara macao", kind: "bird", habitat: "forest", range: "Tropical Americas", region: "amazon", diet: "Fruit and nuts", connected: "A flying seed planter of the rainforest.", fact: "Bright colours help them find each other in green." },
  { slug: "flamingo", common: "American flamingo", latin: "Phoenicopterus ruber", kind: "bird", habitat: "wetland", range: "Caribbean and nearby", region: "caribbean", diet: "Tiny water animals and algae", connected: "Pink comes from their food. You are what you eat, even for birds.", fact: "They filter water upside-down with their beaks." },
  { slug: "toucan", common: "Keel-billed toucan", latin: "Ramphastos sulfuratus", kind: "bird", habitat: "forest", range: "Central America", region: "mesoamerica", diet: "Fruit", connected: "A big bill tosses fruit. Seeds fall far from the parent tree.", fact: "The bill is light, not heavy like stone." },
  { slug: "penguin", common: "Emperor penguin", latin: "Aptenodytes forsteri", kind: "bird", habitat: "polar", range: "Antarctica", region: "polar", diet: "Fish and krill", connected: "A bird that swims. Ice and sea are the nursery.", fact: "Fathers keep the egg warm through winter.", conservation: "Ice change matters" },
  { slug: "albatross", common: "Wandering albatross", latin: "Diomedea exulans", kind: "bird", habitat: "ocean", range: "Southern Ocean", region: "polar", diet: "Squid and fish", connected: "Wings for weeks over waves. The open sea is a road.", fact: "They can glide for hours without a flap." },
  { slug: "pelican", common: "Brown pelican", latin: "Pelecanus occidentalis", kind: "bird", habitat: "ocean", range: "Americas coasts", region: "caribbean", diet: "Fish", connected: "A diving net of a beak.", fact: "The pouch holds fish, not water for long." },
  { slug: "duck", common: "Mallard", latin: "Anas platyrhynchos", kind: "bird", habitat: "wetland", range: "Northern world", region: "britain", diet: "Plants and small water animals", connected: "Ponds in parks are still wild-enough homes.", fact: "Most farm ducks come from mallards." },
  { slug: "chicken", common: "Chicken", latin: "Gallus gallus domesticus", kind: "bird", habitat: "farm", range: "Worldwide farms; wild cousins in Asia", region: "south-asia", diet: "Seeds and insects", connected: "Junglefowl became farm friends. The farm is part of nature too.", fact: "They talk with many different sounds." },
  { slug: "kiwi-bird", common: "Kiwi", latin: "Apteryx australis", kind: "bird", habitat: "forest", range: "New Zealand", region: "pacific", diet: "Soil animals", connected: "A night bird with whiskers like a mammal. Islands make unique lives.", fact: "They have nostrils at the end of the bill." },

  // Mammals land
  { slug: "elephant-african", common: "African savanna elephant", latin: "Loxodonta africana", kind: "mammal", habitat: "savanna", range: "Africa", region: "southern-africa", diet: "Leaves, grass, fruit", connected: "They open forest and spread seeds in dung. Gardeners the size of a bus.", fact: "They remember water holes for years.", conservation: "Needs space and protection" },
  { slug: "lion", common: "Lion", latin: "Panthera leo", kind: "mammal", habitat: "savanna", range: "Africa", region: "southern-africa", diet: "Large animals", connected: "Hunters keep herds moving, which helps grass grow in patches.", fact: "A pride is a family that shares work.", safety: "Wild lions are not pets. Watch films and reserves with adults." },
  { slug: "giraffe", common: "Giraffe", latin: "Giraffa camelopardalis", kind: "mammal", habitat: "savanna", range: "Africa", region: "horn-of-africa", diet: "Leaves high in trees", connected: "Long necks reach the treetops other animals cannot.", fact: "Tongues are dark and tough for thorny leaves." },
  { slug: "zebra", common: "Plains zebra", latin: "Equus quagga", kind: "mammal", habitat: "savanna", range: "Africa", region: "southern-africa", diet: "Grass", connected: "Stripes may confuse biting flies. Grasslands need grazers.", fact: "Each zebra’s stripes are a bit different." },
  { slug: "hippo", common: "Hippopotamus", latin: "Hippopotamus amphibius", kind: "mammal", habitat: "river", range: "Africa", region: "east-africa-fallback", diet: "Grass at night", connected: "Days in the river, nights on land. Dung feeds river life.", fact: "They cannot really swim — they walk underwater.", safety: "Stay far from wild hippos." },
  { slug: "gorilla", common: "Western gorilla", latin: "Gorilla gorilla", kind: "mammal", habitat: "forest", range: "Central Africa", region: "west-africa", diet: "Leaves and fruit", connected: "Forest families. We are relatives in the great ape tree.", fact: "They make nests of leaves to sleep.", conservation: "Needs standing forest" },
  { slug: "chimpanzee", common: "Chimpanzee", latin: "Pan troglodytes", kind: "mammal", habitat: "forest", range: "Africa", region: "west-africa", diet: "Fruit, leaves, some insects", connected: "They use tools. Learning is not only for people.", fact: "Young ones watch and copy elders." },
  { slug: "red-kangaroo", common: "Red kangaroo", latin: "Osphranter rufus", kind: "mammal", habitat: "savanna", range: "Australia", region: "australia", diet: "Grass", connected: "A hopper of dry lands. Joeys grow in a pouch.", fact: "Tails help them balance." },
  { slug: "koala", common: "Koala", latin: "Phascolarctos cinereus", kind: "mammal", habitat: "forest", range: "Australia", region: "australia", diet: "Eucalyptus leaves", connected: "A picky eater of one tree family. Save the tree, save the animal.", fact: "They sleep many hours because the leaves are low energy." },
  { slug: "giant-panda", common: "Giant panda", latin: "Ailuropoda melanoleuca", kind: "mammal", habitat: "forest", range: "China mountains", region: "east-asia", diet: "Bamboo", connected: "A bear that chose a grass. Habitat is a kitchen.", fact: "They hold bamboo with a special wrist bone.", conservation: "Forest corridors help" },
  { slug: "polar-bear", common: "Polar bear", latin: "Ursus maritimus", kind: "mammal", habitat: "polar", range: "Arctic", region: "arctic", diet: "Seals", connected: "Ice is the hunting floor. The polar world is one piece.", fact: "Skin is black under the white fur.", conservation: "Sea ice change is a worry" },
  { slug: "brown-bear", common: "Brown bear", latin: "Ursus arctos", kind: "mammal", habitat: "forest", range: "North and mountains of many lands", region: "north-america", diet: "Plants, fish, sometimes meat", connected: "In some rivers they catch salmon and feed the forest.", fact: "They sleep a long winter rest." },
  { slug: "wolf", common: "Grey wolf", latin: "Canis lupus", kind: "mammal", habitat: "forest", range: "North and wilder lands", region: "north-america", diet: "Large animals", connected: "Packs change how deer eat, which changes how trees grow.", fact: "Dogs are their family." },
  { slug: "red-fox", common: "Red fox", latin: "Vulpes vulpes", kind: "mammal", habitat: "garden", range: "Many countries", region: "britain", diet: "Small animals and fruit", connected: "A twilight neighbour of towns and fields.", fact: "Tails help with balance and warmth." },
  { slug: "deer", common: "Roe deer", latin: "Capreolus capreolus", kind: "mammal", habitat: "forest", range: "Europe", region: "britain", diet: "Leaves and shoots", connected: "Wood edges are their restaurants.", fact: "Kids are called kids? No — fawns." },
  { slug: "rabbit", common: "European rabbit", latin: "Oryctolagus cuniculus", kind: "mammal", habitat: "farm", range: "Iberia originally; many countries now", region: "mediterranean", diet: "Grass", connected: "Diggers of warrens. Soil and grass people.", fact: "They eat some droppings to get more from their food." },
  { slug: "bat", common: "Fruit bat / flying fox", latin: "Pteropus vampyrus", kind: "mammal", habitat: "forest", range: "Southeast Asia", region: "southeast-asia", diet: "Fruit and nectar", connected: "Night pollinators and seed flyers. The dark garden.", fact: "Wings are long hands.", safety: "Do not handle bats. Watch them fly." },
  { slug: "sloth", common: "Brown-throated sloth", latin: "Bradypus variegatus", kind: "mammal", habitat: "forest", range: "Tropical Americas", region: "amazon", diet: "Leaves", connected: "Algae can grow in their fur. A slow moving garden.", fact: "They come down to the ground about once a week." },
  { slug: "camel", common: "Dromedary camel", latin: "Camelus dromedarius", kind: "mammal", habitat: "savanna", range: "North Africa and West Asia", region: "middle-east", diet: "Dry plants", connected: "The hump stores fat, not a magic water tank. Desert partner of people.", fact: "They can close nostrils in sandstorms." },
  { slug: "llama", common: "Llama", latin: "Lama glama", kind: "mammal", habitat: "farm", range: "Andes", region: "andes", diet: "Grass", connected: "A mountain helper of people. Cousin of wild guanaco.", fact: "They hum to their families." },
  { slug: "cow", common: "Cattle", latin: "Bos taurus", kind: "mammal", habitat: "farm", range: "Worldwide farms; wild aurochs were European", region: "britain", diet: "Grass", connected: "Farms are living systems too. Grass, dung, soil, milk.", fact: "They have four stomach rooms for grass." },
  { slug: "sheep", common: "Sheep", latin: "Ovis aries", kind: "mammal", habitat: "farm", range: "Worldwide farms", region: "middle-east", diet: "Grass", connected: "Wool, grass and hills. People and sheep grew up together.", fact: "Flocks follow a leader." },
  { slug: "goat", common: "Goat", latin: "Capra hircus", kind: "mammal", habitat: "farm", range: "Worldwide; wild cousins in mountains", region: "middle-east", diet: "Leaves and grass", connected: "Browsers of shrubs. They can clear and they can over-nibble — care matters.", fact: "Pupils look like bars." },
  { slug: "horse", common: "Horse", latin: "Equus ferus caballus", kind: "mammal", habitat: "farm", range: "Worldwide; wild origins in Eurasia", region: "central-asia", diet: "Grass", connected: "A partner of people on grass seas.", fact: "They can sleep standing." },
  { slug: "pig", common: "Pig", latin: "Sus domesticus", kind: "mammal", habitat: "farm", range: "Worldwide farms; wild boar in forests", region: "east-asia", diet: "Many foods", connected: "Excellent snouts find food in soil. Forest cousins still live wild.", fact: "They are very clean if they have space." },
  { slug: "dog", common: "Dog", latin: "Canis familiaris", kind: "mammal", habitat: "farm", range: "Worldwide with people", region: "worldwide", diet: "People’s care", connected: "Wolves who stayed. A living bridge between wild and home.", fact: "They read our faces.", safety: "Ask before you stroke a dog you do not know." },
  { slug: "cat", common: "Domestic cat", latin: "Felis catus", kind: "mammal", habitat: "farm", range: "Worldwide with people", region: "africa-north", diet: "Meat; people feed them", connected: "Night hunters of mice. Also a risk to wild birds — bells and nights in can help.", fact: "Whiskers measure gaps." },

  // Reptiles amphibians
  { slug: "frog", common: "Common frog", latin: "Rana temporaria", kind: "amphibian", habitat: "wetland", range: "Europe", region: "britain", diet: "Insects", connected: "Eggs in jelly, tadpoles in ponds, frogs on land. Water starts the story.", fact: "Tadpoles grow legs and lose tails." },
  { slug: "tree-frog", common: "Red-eyed tree frog", latin: "Agalychnis callidryas", kind: "amphibian", habitat: "forest", range: "Central America", region: "mesoamerica", diet: "Insects", connected: "Leaves over ponds are nurseries.", fact: "Bright red eyes can startle a hunter." },
  { slug: "toad", common: "Common toad", latin: "Bufo bufo", kind: "amphibian", habitat: "garden", range: "Europe", region: "britain", diet: "Insects and slugs", connected: "A night helper of the vegetable patch.", fact: "They walk more than they hop." },
  { slug: "newt", common: "Great crested newt", latin: "Triturus cristatus", kind: "amphibian", habitat: "wetland", range: "Europe", region: "britain", diet: "Small water animals", connected: "Ponds without fish can be newt palaces.", fact: "Males grow a crest in spring.", conservation: "Protected in some countries" },
  { slug: "gecko", common: "Tokay gecko", latin: "Gekko gecko", kind: "reptile", habitat: "forest", range: "Southeast Asia", region: "southeast-asia", diet: "Insects", connected: "Feet stick with tiny hairs. Night climbers of walls and trees.", fact: "They bark a sound like their name." },
  { slug: "iguana", common: "Green iguana", latin: "Iguana iguana", kind: "reptile", habitat: "forest", range: "Tropical Americas", region: "caribbean", diet: "Leaves", connected: "A sun-basking leaf eater in the trees.", fact: "A dewlap is the flap under the chin." },
  { slug: "tortoise", common: "Aldabra giant tortoise", latin: "Aldabrachelys gigantea", kind: "reptile", habitat: "savanna", range: "Seychelles islands", region: "east-africa-fallback", diet: "Plants", connected: "Slow gardeners who live a very long time.", fact: "Shells grow with them." },
  { slug: "crocodile", common: "Nile crocodile", latin: "Crocodylus niloticus", kind: "reptile", habitat: "river", range: "Africa", region: "east-africa-fallback", diet: "Fish and animals at the edge", connected: "An ancient river hunter. Banks are their doors.", fact: "They can walk with their bodies high.", safety: "Never go near wild crocodiles." },
  { slug: "snake-garter", common: "Garter snake", latin: "Thamnophis sirtalis", kind: "reptile", habitat: "garden", range: "North America", region: "north-america", diet: "Worms and frogs", connected: "Most snakes want to be left alone. They eat garden pests.", fact: "They have babies, not always eggs.", safety: "Look, do not pick up wild snakes." },

  // Extra worldwide connectors
  { slug: "krill", common: "Antarctic krill", latin: "Euphausia superba", kind: "invertebrate", habitat: "polar", range: "Southern Ocean", region: "polar", diet: "Tiny ocean plants", connected: "Whales, penguins and seals feast on krill. Ocean plants feed the giants.", fact: "There can be billions in a swarm." },
  { slug: "plankton-note", common: "Phytoplankton (ocean plants)", latin: "Many kinds of tiny algae", kind: "invertebrate", habitat: "ocean", range: "All oceans", region: "worldwide", diet: "Sunlight and seawater minerals", connected: "These are plants of the sea. They make oxygen and feed fish. Everything is connected.", fact: "Many are too small to see, yet they colour whole seas green." },
];

function expand(s: Seed): AnimalRecord {
  const q = encodeURIComponent(s.latin.split("(")[0].trim());
  const region = s.region === "east-africa-fallback" ? "horn-of-africa" : s.region === "africa-north" ? "middle-east" : s.region === "polar" ? "pacific" : s.region === "arctic" ? "north-america" : s.region === "worldwide" ? "caribbean" : s.region;
  return {
    slug: s.slug,
    commonName: s.common,
    scientificName: s.latin,
    kind: s.kind,
    habitat: s.habitat,
    nativeRange: s.range,
    mapRegion: region,
    diet: s.diet,
    connected: s.connected,
    childFact: s.fact,
    safety: s.safety ?? "Wild animals are not toys. Look with an adult. Do not chase, grab or feed without a keeper.",
    conservation: s.conservation ?? "Common in some places, rare in others. Care for homes, not just famous faces.",
    names: s.names ?? [],
    editorialStatus: "in_review",
    claims: [
      {
        id: `${s.slug}-name`,
        text: `${s.latin} is the scientific name used here for ${s.common}.`,
        category: "ecology",
        evidence: "plausible",
        editorialStatus: "in_review",
        sources: [
          {
            title: s.latin,
            publisher: "IUCN Red List search",
            url: `https://www.iucnredlist.org/search?query=${q}`,
            accessed: "2026-09-14",
            notes: "Look up the accepted name and conservation status. Catalogue records wait for editor review.",
          },
        ],
      },
    ],
  };
}

export const catalogAnimals: AnimalRecord[] = SEEDS.map(expand);
