import type { PlantKind, PlantRecord } from "./schema";

type Seed = {
  slug: string;
  common: string;
  latin: string;
  kind: PlantKind;
  origin: string;
  region: string;
  grow?: string[];
  names?: string[];
  recipes?: string[];
  safety?: string;
};

const SEEDS: Seed[] = [
  { slug: "orange", common: "Orange", latin: "Citrus × sinensis", kind: "fruit", origin: "Southern China", region: "east-asia", grow: ["Mediterranean", "Americas", "Africa"], names: ["Naranja"], recipes: ["Fresh fruit", "Juice"] },
  { slug: "lemon", common: "Lemon", latin: "Citrus limon", kind: "fruit", origin: "Asia (citrus family)", region: "east-asia", grow: ["Mediterranean", "California", "Argentina"], names: ["Limón"], recipes: ["Juice", "Preserves"] },
  { slug: "lime", common: "Lime", latin: "Citrus aurantiifolia / Citrus latifolia", kind: "fruit", origin: "Southeast Asia", region: "southeast-asia", grow: ["Caribbean", "Mexico", "India"], names: ["Limón agrio"], recipes: ["Juice", "Pickle"] },
  { slug: "grapefruit", common: "Grapefruit", latin: "Citrus × paradisi", kind: "fruit", origin: "Caribbean (hybrid)", region: "caribbean", grow: ["Florida", "South Africa", "Israel"], recipes: ["Breakfast fruit", "Juice"] },
  { slug: "tangerine", common: "Tangerine", latin: "Citrus reticulata", kind: "fruit", origin: "East Asia", region: "east-asia", names: ["Mandarin"], recipes: ["Fresh fruit"] },
  { slug: "clementine", common: "Clementine", latin: "Citrus × clementina", kind: "fruit", origin: "Mediterranean citrus breeding", region: "mediterranean", recipes: ["Lunchbox fruit"] },
  { slug: "pomelo", common: "Pomelo", latin: "Citrus maxima", kind: "fruit", origin: "Southeast Asia", region: "southeast-asia", names: ["Shaddock"], recipes: ["Fresh segments"] },
  { slug: "kumquat", common: "Kumquat", latin: "Citrus japonica", kind: "fruit", origin: "East Asia", region: "east-asia", recipes: ["Eat whole", "Preserve"] },
  { slug: "papaya", common: "Papaya", latin: "Carica papaya", kind: "fruit", origin: "Tropical Americas", region: "mesoamerica", grow: ["Caribbean", "Africa", "Asia"], names: ["Pawpaw (some regions)"], recipes: ["Fresh fruit", "Salad"] },
  { slug: "pineapple", common: "Pineapple", latin: "Ananas comosus", kind: "fruit", origin: "South America", region: "amazon", grow: ["Caribbean", "Hawaii", "Philippines"], recipes: ["Fresh fruit", "Grill"] },
  { slug: "passionfruit", common: "Passion fruit", latin: "Passiflora edulis", kind: "fruit", origin: "South America", region: "andes", grow: ["Caribbean", "Africa", "Australia"], names: ["Maracuyá"], recipes: ["Juice", "Pulp"] },
  { slug: "guava", common: "Guava", latin: "Psidium guajava", kind: "fruit", origin: "Tropical Americas", region: "amazon", grow: ["Caribbean", "South Asia"], names: ["Guayaba"], recipes: ["Juice", "Jam"] },
  { slug: "lychee", common: "Lychee", latin: "Litchi chinensis", kind: "fruit", origin: "Southern China", region: "east-asia", recipes: ["Fresh fruit"] },
  { slug: "rambutan", common: "Rambutan", latin: "Nephelium lappaceum", kind: "fruit", origin: "Southeast Asia", region: "southeast-asia", recipes: ["Fresh fruit"] },
  { slug: "longan", common: "Longan", latin: "Dimocarpus longan", kind: "fruit", origin: "Southeast Asia", region: "southeast-asia", recipes: ["Fresh fruit"] },
  { slug: "durian", common: "Durian", latin: "Durio zibethinus", kind: "fruit", origin: "Southeast Asia", region: "southeast-asia", recipes: ["Fresh pulp"], safety: "Strong smell. Seeds and husk are not the eating part." },
  { slug: "jackfruit", common: "Jackfruit", latin: "Artocarpus heterophyllus", kind: "fruit", origin: "South and Southeast Asia", region: "south-asia", recipes: ["Ripe fruit", "Young jackfruit cooked"] },
  { slug: "starfruit", common: "Starfruit", latin: "Averrhoa carambola", kind: "fruit", origin: "Southeast Asia", region: "southeast-asia", names: ["Carambola"], recipes: ["Fresh slices"], safety: "People with kidney disease should ask a doctor before eating starfruit." },
  { slug: "dragonfruit", common: "Dragon fruit", latin: "Selenicereus undatus", kind: "fruit", origin: "Central America", region: "mesoamerica", grow: ["Vietnam", "Caribbean"], names: ["Pitaya"], recipes: ["Fresh fruit"] },
  { slug: "pomegranate", common: "Pomegranate", latin: "Punica granatum", kind: "fruit", origin: "West Asia / Iran region", region: "middle-east", recipes: ["Arils", "Juice"] },
  { slug: "fig", common: "Fig", latin: "Ficus carica", kind: "fruit", origin: "West Asia / Mediterranean", region: "mediterranean", recipes: ["Fresh", "Dried"] },
  { slug: "date", common: "Date", latin: "Phoenix dactylifera", kind: "fruit", origin: "West Asia / North Africa", region: "middle-east", recipes: ["Dried fruit", "Paste"] },
  { slug: "grape", common: "Grape", latin: "Vitis vinifera", kind: "fruit", origin: "West Asia / Mediterranean", region: "mediterranean", recipes: ["Fresh", "Raisins"] },
  { slug: "pear", common: "Pear", latin: "Pyrus communis", kind: "fruit", origin: "Europe and West Asia", region: "britain", recipes: ["Fresh", "Poached"] },
  { slug: "peach", common: "Peach", latin: "Prunus persica", kind: "fruit", origin: "China", region: "east-asia", recipes: ["Fresh", "Jam"] },
  { slug: "nectarine", common: "Nectarine", latin: "Prunus persica var. nucipersica", kind: "fruit", origin: "China (peach family)", region: "east-asia", recipes: ["Fresh fruit"] },
  { slug: "plum", common: "Plum", latin: "Prunus domestica", kind: "fruit", origin: "Europe / West Asia", region: "britain", recipes: ["Fresh", "Prunes"] },
  { slug: "apricot", common: "Apricot", latin: "Prunus armeniaca", kind: "fruit", origin: "Central Asia / China", region: "central-asia", recipes: ["Fresh", "Dried"] },
  { slug: "cherry", common: "Cherry", latin: "Prunus avium", kind: "fruit", origin: "Europe and West Asia", region: "britain", recipes: ["Fresh fruit"], safety: "Do not eat the stones." },
  { slug: "strawberry", common: "Strawberry", latin: "Fragaria × ananassa", kind: "fruit", origin: "Americas × Europe garden hybrid", region: "north-america", recipes: ["Fresh", "Jam"] },
  { slug: "raspberry", common: "Raspberry", latin: "Rubus idaeus", kind: "fruit", origin: "Europe and Asia", region: "britain", recipes: ["Fresh", "Jam"] },
  { slug: "blackberry", common: "Blackberry", latin: "Rubus fruticosus agg.", kind: "fruit", origin: "Europe and nearby", region: "britain", recipes: ["Fresh", "Crumble"] },
  { slug: "blueberry", common: "Blueberry", latin: "Vaccinium corymbosum", kind: "fruit", origin: "North America", region: "north-america", recipes: ["Fresh", "Muffins"] },
  { slug: "cranberry", common: "Cranberry", latin: "Vaccinium macrocarpon", kind: "fruit", origin: "North America", region: "north-america", recipes: ["Sauce", "Juice"] },
  { slug: "kiwi", common: "Kiwifruit", latin: "Actinidia deliciosa", kind: "fruit", origin: "China", region: "east-asia", grow: ["New Zealand", "Italy"], names: ["Chinese gooseberry"], recipes: ["Fresh fruit"] },
  { slug: "persimmon", common: "Persimmon", latin: "Diospyros kaki", kind: "fruit", origin: "East Asia", region: "east-asia", recipes: ["Ripe fruit"] },
  { slug: "watermelon", common: "Watermelon", latin: "Citrullus lanatus", kind: "fruit", origin: "Africa", region: "southern-africa", recipes: ["Fresh slices"] },
  { slug: "cantaloupe", common: "Cantaloupe melon", latin: "Cucumis melo", kind: "fruit", origin: "Africa / West Asia (melon family)", region: "middle-east", recipes: ["Fresh fruit"] },
  { slug: "honeydew", common: "Honeydew melon", latin: "Cucumis melo", kind: "fruit", origin: "Africa / West Asia (melon family)", region: "middle-east", recipes: ["Fresh fruit"] },
  { slug: "avocado", common: "Avocado", latin: "Persea americana", kind: "fruit", origin: "Mesoamerica", region: "mesoamerica", recipes: ["Mash", "Sliced"] },
  { slug: "olive", common: "Olive", latin: "Olea europaea", kind: "fruit", origin: "Mediterranean", region: "mediterranean", recipes: ["Table olives", "Oil"] },
  { slug: "tomato", common: "Tomato", latin: "Solanum lycopersicum", kind: "fruit", origin: "Andes / Mesoamerica", region: "andes", grow: ["Worldwide gardens"], recipes: ["Salad", "Sauce"] },
  { slug: "cucumber", common: "Cucumber", latin: "Cucumis sativus", kind: "vegetable", origin: "South Asia", region: "south-asia", recipes: ["Salad", "Pickle"] },
  { slug: "aubergine", common: "Aubergine / eggplant", latin: "Solanum melongena", kind: "vegetable", origin: "South and East Asia", region: "south-asia", recipes: ["Roast", "Stew"] },
  { slug: "bell-pepper", common: "Sweet pepper", latin: "Capsicum annuum", kind: "vegetable", origin: "Mesoamerica", region: "mesoamerica", recipes: ["Raw", "Roast"] },
  { slug: "chilli", common: "Chilli pepper", latin: "Capsicum annuum / Capsicum frutescens", kind: "spice", origin: "Mesoamerica", region: "mesoamerica", recipes: ["Spice", "Sauce"], safety: "Hot. Keep away from eyes. Not a dare food for little children." },
  { slug: "courgette", common: "Courgette / zucchini", latin: "Cucurbita pepo", kind: "vegetable", origin: "Mesoamerica (squash family)", region: "mesoamerica", recipes: ["Grill", "Bake"] },
  { slug: "pumpkin", common: "Pumpkin", latin: "Cucurbita pepo / C. maxima", kind: "vegetable", origin: "Americas", region: "mesoamerica", recipes: ["Roast", "Soup"] },
  { slug: "butternut", common: "Butternut squash", latin: "Cucurbita moschata", kind: "vegetable", origin: "Americas", region: "mesoamerica", recipes: ["Roast", "Soup"] },
  { slug: "plantain", common: "Plantain", latin: "Musa (AAB / ABB cooking groups)", kind: "fruit", origin: "Southeast Asia (Musa family)", region: "west-africa", grow: ["Caribbean", "West Africa"], recipes: ["Fried", "Boiled"] },
  { slug: "tamarind", common: "Tamarind", latin: "Tamarindus indica", kind: "fruit", origin: "Africa", region: "west-africa", grow: ["India", "Caribbean"], recipes: ["Pulp", "Drink"] },
  { slug: "mangosteen", common: "Mangosteen", latin: "Garcinia mangostana", kind: "fruit", origin: "Southeast Asia", region: "southeast-asia", recipes: ["Fresh arils"] },
  { slug: "custard-apple", common: "Custard apple", latin: "Annona reticulata", kind: "fruit", origin: "Tropical Americas", region: "caribbean", recipes: ["Fresh pulp"], safety: "Do not eat the seeds." },
  { slug: "sugar-apple", common: "Sugar apple / sweetsop", latin: "Annona squamosa", kind: "fruit", origin: "Tropical Americas", region: "caribbean", recipes: ["Fresh pulp"], safety: "Do not eat the seeds." },
  { slug: "cherimoya", common: "Cherimoya", latin: "Annona cherimola", kind: "fruit", origin: "Andes", region: "andes", recipes: ["Fresh pulp"], safety: "Do not eat the seeds." },
  { slug: "sapodilla", common: "Sapodilla", latin: "Manilkara zapota", kind: "fruit", origin: "Mesoamerica", region: "mesoamerica", names: ["Nispero"], recipes: ["Ripe fruit"] },
  { slug: "acerola", common: "Acerola", latin: "Malpighia emarginata", kind: "fruit", origin: "Tropical Americas", region: "caribbean", recipes: ["Juice"] },
  { slug: "acai", common: "Açaí", latin: "Euterpe oleracea", kind: "fruit", origin: "Amazon", region: "amazon", recipes: ["Pulp"], safety: "Food, not a miracle medicine." },
  { slug: "cashew-apple", common: "Cashew apple", latin: "Anacardium occidentale", kind: "fruit", origin: "Tropical Americas", region: "amazon", recipes: ["Juice"], safety: "Never eat raw cashew shells. Nuts are processed." },
  { slug: "mulberry", common: "Mulberry", latin: "Morus nigra / Morus alba", kind: "fruit", origin: "West and East Asia", region: "middle-east", recipes: ["Fresh", "Jam"] },
  { slug: "elderberry", common: "Elderberry", latin: "Sambucus nigra", kind: "wild", origin: "Europe", region: "britain", recipes: ["Cooked syrup"], safety: "Raw berries and other parts can be unkind to tummies. Cook with an adult. Not a medicine claim." },
  { slug: "gooseberry", common: "Gooseberry", latin: "Ribes uva-crispa", kind: "fruit", origin: "Europe", region: "britain", recipes: ["Fool", "Jam"] },
  { slug: "blackcurrant", common: "Blackcurrant", latin: "Ribes nigrum", kind: "fruit", origin: "Europe and Asia", region: "britain", recipes: ["Juice", "Jam"] },
  { slug: "redcurrant", common: "Redcurrant", latin: "Ribes rubrum", kind: "fruit", origin: "Europe", region: "britain", recipes: ["Jelly"] },
  { slug: "quince", common: "Quince", latin: "Cydonia oblonga", kind: "fruit", origin: "West and Central Asia", region: "middle-east", recipes: ["Cooked paste"] },
  { slug: "loquat", common: "Loquat", latin: "Eriobotrya japonica", kind: "fruit", origin: "East Asia", region: "east-asia", recipes: ["Fresh fruit"] },
  { slug: "jujube", common: "Jujube", latin: "Ziziphus jujuba", kind: "fruit", origin: "East Asia", region: "east-asia", recipes: ["Fresh", "Dried"] },
  { slug: "feijoa", common: "Feijoa", latin: "Acca sellowiana", kind: "fruit", origin: "South America", region: "andes", recipes: ["Fresh fruit"] },
  { slug: "prickly-pear", common: "Prickly pear", latin: "Opuntia ficus-indica", kind: "fruit", origin: "Mesoamerica", region: "mesoamerica", recipes: ["Peeled fruit"], safety: "Spines must be removed by an adult." },
  { slug: "ugli", common: "Ugli fruit", latin: "Citrus reticulata × Citrus paradisi", kind: "fruit", origin: "Jamaica (citrus hybrid)", region: "caribbean", recipes: ["Fresh fruit"] },
  { slug: "cape-gooseberry", common: "Cape gooseberry", latin: "Physalis peruviana", kind: "fruit", origin: "Andes", region: "andes", recipes: ["Fresh", "Jam"] },
  { slug: "jabuticaba", common: "Jabuticaba", latin: "Plinia cauliflora", kind: "fruit", origin: "Brazil", region: "amazon", recipes: ["Fresh fruit"] },
  { slug: "breadnut", common: "Breadnut", latin: "Artocarpus camansi", kind: "fruit", origin: "Pacific / New Guinea", region: "pacific", recipes: ["Roasted seeds"] },
  { slug: "soursop-relative-pawpaw", common: "American pawpaw", latin: "Asimina triloba", kind: "fruit", origin: "Eastern North America", region: "north-america", recipes: ["Ripe pulp"] },

  { slug: "carrot", common: "Carrot", latin: "Daucus carota", kind: "vegetable", origin: "Central Asia / West Asia", region: "central-asia", recipes: ["Raw", "Roast"] },
  { slug: "parsnip", common: "Parsnip", latin: "Pastinaca sativa", kind: "vegetable", origin: "Europe", region: "britain", recipes: ["Roast"] },
  { slug: "beetroot", common: "Beetroot", latin: "Beta vulgaris", kind: "vegetable", origin: "Mediterranean / West Asia", region: "mediterranean", recipes: ["Roast", "Salad"] },
  { slug: "radish", common: "Radish", latin: "Raphanus sativus", kind: "vegetable", origin: "East Mediterranean / Asia", region: "mediterranean", recipes: ["Raw"] },
  { slug: "turnip", common: "Turnip", latin: "Brassica rapa", kind: "vegetable", origin: "Europe / West Asia", region: "britain", recipes: ["Mash", "Stew"] },
  { slug: "swede", common: "Swede / rutabaga", latin: "Brassica napus", kind: "vegetable", origin: "Northern Europe", region: "britain", recipes: ["Mash"] },
  { slug: "onion", common: "Onion", latin: "Allium cepa", kind: "vegetable", origin: "West Asia", region: "middle-east", recipes: ["Cooked base"] },
  { slug: "garlic", common: "Garlic", latin: "Allium sativum", kind: "vegetable", origin: "West and Central Asia", region: "middle-east", recipes: ["Cooked", "Roast"] },
  { slug: "leek", common: "Leek", latin: "Allium ampeloprasum", kind: "vegetable", origin: "Mediterranean", region: "mediterranean", recipes: ["Soup"] },
  { slug: "shallot", common: "Shallot", latin: "Allium cepa Aggregatum", kind: "vegetable", origin: "West Asia", region: "middle-east", recipes: ["Cooked"] },
  { slug: "spring-onion", common: "Spring onion", latin: "Allium fistulosum / A. cepa", kind: "vegetable", origin: "East Asia / West Asia", region: "east-asia", recipes: ["Salad"] },
  { slug: "cabbage", common: "Cabbage", latin: "Brassica oleracea", kind: "vegetable", origin: "Europe", region: "britain", recipes: ["Boil", "Slaw"] },
  { slug: "kale", common: "Kale", latin: "Brassica oleracea", kind: "vegetable", origin: "Europe", region: "britain", recipes: ["Saute"] },
  { slug: "broccoli", common: "Broccoli", latin: "Brassica oleracea", kind: "vegetable", origin: "Mediterranean Europe", region: "mediterranean", recipes: ["Steam", "Roast"] },
  { slug: "cauliflower", common: "Cauliflower", latin: "Brassica oleracea", kind: "vegetable", origin: "Mediterranean", region: "mediterranean", recipes: ["Roast", "Curry"] },
  { slug: "brussels-sprout", common: "Brussels sprout", latin: "Brassica oleracea", kind: "vegetable", origin: "Europe", region: "britain", recipes: ["Roast"] },
  { slug: "kohlrabi", common: "Kohlrabi", latin: "Brassica oleracea", kind: "vegetable", origin: "Europe", region: "britain", recipes: ["Raw", "Roast"] },
  { slug: "bok-choy", common: "Bok choy", latin: "Brassica rapa subsp. chinensis", kind: "vegetable", origin: "East Asia", region: "east-asia", recipes: ["Stir-fry"] },
  { slug: "napa-cabbage", common: "Napa cabbage", latin: "Brassica rapa subsp. pekinensis", kind: "vegetable", origin: "East Asia", region: "east-asia", recipes: ["Kimchi", "Soup"] },
  { slug: "spinach", common: "Spinach", latin: "Spinacia oleracea", kind: "vegetable", origin: "West Asia", region: "middle-east", recipes: ["Wilted", "Salad"] },
  { slug: "chard", common: "Swiss chard", latin: "Beta vulgaris subsp. cicla", kind: "vegetable", origin: "Mediterranean", region: "mediterranean", recipes: ["Saute"] },
  { slug: "lettuce", common: "Lettuce", latin: "Lactuca sativa", kind: "vegetable", origin: "Mediterranean", region: "mediterranean", recipes: ["Salad"] },
  { slug: "rocket", common: "Rocket / arugula", latin: "Eruca vesicaria", kind: "vegetable", origin: "Mediterranean", region: "mediterranean", recipes: ["Salad"] },
  { slug: "watercress", common: "Watercress", latin: "Nasturtium officinale", kind: "vegetable", origin: "Europe and Asia", region: "britain", recipes: ["Salad"], safety: "Grow or buy from clean water. Wild watercress needs expert care." },
  { slug: "collard", common: "Collard greens", latin: "Brassica oleracea", kind: "vegetable", origin: "Europe", region: "britain", grow: ["West Africa diaspora kitchens", "US South"], recipes: ["Stew"] },
  { slug: "callaloo", common: "Callaloo (amaranth greens)", latin: "Amaranthus spp.", kind: "vegetable", origin: "Americas / Africa (species vary)", region: "caribbean", recipes: ["Steamed greens"] },
  { slug: "okra", common: "Okra", latin: "Abelmoschus esculentus", kind: "vegetable", origin: "Africa", region: "west-africa", recipes: ["Stew", "Fry"] },
  { slug: "sweetcorn", common: "Sweetcorn / maize", latin: "Zea mays", kind: "vegetable", origin: "Mesoamerica", region: "mesoamerica", recipes: ["Boiled", "Roast"] },
  { slug: "pea", common: "Garden pea", latin: "Pisum sativum", kind: "legume", origin: "West Asia / Fertile Crescent", region: "middle-east", recipes: ["Boiled"] },
  { slug: "green-bean", common: "Green bean", latin: "Phaseolus vulgaris", kind: "legume", origin: "Mesoamerica / Andes", region: "andes", recipes: ["Steam"] },
  { slug: "broad-bean", common: "Broad bean / fava", latin: "Vicia faba", kind: "legume", origin: "West Asia / North Africa", region: "middle-east", recipes: ["Boiled"] },
  { slug: "runner-bean", common: "Runner bean", latin: "Phaseolus coccineus", kind: "legume", origin: "Mesoamerica", region: "mesoamerica", recipes: ["Boiled"] },
  { slug: "asparagus", common: "Asparagus", latin: "Asparagus officinalis", kind: "vegetable", origin: "Europe / West Asia", region: "mediterranean", recipes: ["Steam"] },
  { slug: "artichoke", common: "Globe artichoke", latin: "Cynara cardunculus", kind: "vegetable", origin: "Mediterranean", region: "mediterranean", recipes: ["Steam"] },
  { slug: "fennel", common: "Florence fennel", latin: "Foeniculum vulgare", kind: "vegetable", origin: "Mediterranean", region: "mediterranean", recipes: ["Raw", "Roast"] },
  { slug: "celery", common: "Celery", latin: "Apium graveolens", kind: "vegetable", origin: "Mediterranean", region: "mediterranean", recipes: ["Raw", "Soup"] },
  { slug: "sweet-potato", common: "Sweet potato", latin: "Ipomoea batatas", kind: "vegetable", origin: "Tropical Americas", region: "amazon", recipes: ["Roast", "Mash"] },
  { slug: "cassava", common: "Cassava / yuca", latin: "Manihot esculenta", kind: "vegetable", origin: "Tropical Americas", region: "amazon", recipes: ["Cooked mash", "Farine"], safety: "Must be prepared correctly. Never eat raw bitter cassava. Adult cooking only." },
  { slug: "taro", common: "Taro", latin: "Colocasia esculenta", kind: "vegetable", origin: "Southeast Asia / Pacific", region: "pacific", recipes: ["Boiled", "Poi"], safety: "Cook well. Raw taro can irritate the mouth." },
  { slug: "dasheen", common: "Dasheen", latin: "Colocasia esculenta", kind: "vegetable", origin: "Southeast Asia / Pacific", region: "caribbean", recipes: ["Boiled"] },
  { slug: "eddo", common: "Eddo", latin: "Colocasia / Alocasia related aroids", kind: "vegetable", origin: "Asia / Pacific", region: "caribbean", recipes: ["Boiled"], safety: "Cook well." },
  { slug: "celeriac", common: "Celeriac", latin: "Apium graveolens var. rapaceum", kind: "vegetable", origin: "Mediterranean", region: "mediterranean", recipes: ["Mash", "Remoulade"] },

  { slug: "basil", common: "Basil", latin: "Ocimum basilicum", kind: "herb", origin: "South and Southeast Asia", region: "south-asia", recipes: ["Fresh herb"] },
  { slug: "mint", common: "Mint", latin: "Mentha spp.", kind: "herb", origin: "Europe and Asia", region: "britain", recipes: ["Tea", "Sauce"] },
  { slug: "thyme", common: "Thyme", latin: "Thymus vulgaris", kind: "herb", origin: "Mediterranean", region: "mediterranean", recipes: ["Stew"] },
  { slug: "rosemary", common: "Rosemary", latin: "Salvia rosmarinus", kind: "herb", origin: "Mediterranean", region: "mediterranean", recipes: ["Roast"] },
  { slug: "sage", common: "Sage", latin: "Salvia officinalis", kind: "herb", origin: "Mediterranean", region: "mediterranean", recipes: ["Cooked herb"] },
  { slug: "oregano", common: "Oregano", latin: "Origanum vulgare", kind: "herb", origin: "Mediterranean", region: "mediterranean", recipes: ["Sauce"] },
  { slug: "parsley", common: "Parsley", latin: "Petroselinum crispum", kind: "herb", origin: "Mediterranean", region: "mediterranean", recipes: ["Garnish", "Sauce"] },
  { slug: "coriander", common: "Coriander / cilantro", latin: "Coriandrum sativum", kind: "herb", origin: "West Asia / Mediterranean", region: "middle-east", recipes: ["Leaves", "Seeds"] },
  { slug: "dill", common: "Dill", latin: "Anethum graveolens", kind: "herb", origin: "West Asia / Mediterranean", region: "middle-east", recipes: ["Fish", "Pickle"] },
  { slug: "chives", common: "Chives", latin: "Allium schoenoprasum", kind: "herb", origin: "Europe and Asia", region: "britain", recipes: ["Fresh"] },
  { slug: "lemongrass", common: "Lemongrass", latin: "Cymbopogon citratus", kind: "herb", origin: "South and Southeast Asia", region: "southeast-asia", recipes: ["Tea", "Soup"] },
  { slug: "ginger", common: "Ginger", latin: "Zingiber officinale", kind: "spice", origin: "South and Southeast Asia", region: "south-asia", recipes: ["Tea", "Stir-fry"] },
  { slug: "turmeric", common: "Turmeric", latin: "Curcuma longa", kind: "spice", origin: "South Asia", region: "south-asia", recipes: ["Curry"], safety: "Food spice, not a medicine claim." },
  { slug: "galangal", common: "Galangal", latin: "Alpinia galanga", kind: "spice", origin: "Southeast Asia", region: "southeast-asia", recipes: ["Soup"] },
  { slug: "scallion-caribbean", common: "Caribbean escallion", latin: "Allium fistulosum (kitchen use)", kind: "herb", origin: "East Asia, loved in Caribbean kitchens", region: "caribbean", recipes: ["Seasoning"] },

  { slug: "wheat", common: "Wheat", latin: "Triticum aestivum", kind: "grain", origin: "Fertile Crescent", region: "middle-east", recipes: ["Bread", "Pasta"] },
  { slug: "barley", common: "Barley", latin: "Hordeum vulgare", kind: "grain", origin: "Fertile Crescent", region: "middle-east", recipes: ["Soup", "Bread"] },
  { slug: "oats", common: "Oats", latin: "Avena sativa", kind: "grain", origin: "Europe / West Asia", region: "britain", recipes: ["Porridge"] },
  { slug: "rye", common: "Rye", latin: "Secale cereale", kind: "grain", origin: "West Asia / Europe", region: "britain", recipes: ["Bread"] },
  { slug: "maize", common: "Maize / corn", latin: "Zea mays", kind: "grain", origin: "Mesoamerica", region: "mesoamerica", recipes: ["Meal", "Tortilla"] },
  { slug: "millet", common: "Pearl millet", latin: "Pennisetum glaucum", kind: "grain", origin: "West Africa", region: "west-africa", recipes: ["Porridge"] },
  { slug: "sorghum", common: "Sorghum", latin: "Sorghum bicolor", kind: "grain", origin: "Africa", region: "east-africa-fallback", grow: ["Africa", "India"], recipes: ["Porridge", "Bread"] },
  { slug: "quinoa", common: "Quinoa", latin: "Chenopodium quinoa", kind: "grain", origin: "Andes", region: "andes", recipes: ["Boiled grain"] },
  { slug: "amaranth-grain", common: "Amaranth grain", latin: "Amaranthus spp.", kind: "grain", origin: "Mesoamerica / Andes", region: "mesoamerica", recipes: ["Porridge"] },
  { slug: "buckwheat", common: "Buckwheat", latin: "Fagopyrum esculentum", kind: "grain", origin: "East Asia", region: "east-asia", recipes: ["Noodles", "Pancakes"] },
  { slug: "fonio", common: "Fonio", latin: "Digitaria exilis", kind: "grain", origin: "West Africa", region: "west-africa", recipes: ["Couscous-style"] },

  { slug: "almond", common: "Almond", latin: "Prunus dulcis", kind: "nut", origin: "West Asia", region: "middle-east", recipes: ["Snack", "Paste"], safety: "Nut allergy can be serious." },
  { slug: "walnut", common: "Walnut", latin: "Juglans regia", kind: "nut", origin: "Central Asia / West Asia", region: "central-asia", recipes: ["Baking"], safety: "Nut allergy can be serious." },
  { slug: "pecan", common: "Pecan", latin: "Carya illinoinensis", kind: "nut", origin: "North America", region: "north-america", recipes: ["Baking"], safety: "Nut allergy can be serious." },
  { slug: "hazelnut", common: "Hazelnut", latin: "Corylus avellana", kind: "nut", origin: "Europe and West Asia", region: "britain", recipes: ["Paste"], safety: "Nut allergy can be serious." },
  { slug: "cashew", common: "Cashew", latin: "Anacardium occidentale", kind: "nut", origin: "Tropical Americas", region: "amazon", recipes: ["Roasted"], safety: "Never eat raw shells. Nut allergy can be serious." },
  { slug: "pistachio", common: "Pistachio", latin: "Pistacia vera", kind: "nut", origin: "West and Central Asia", region: "middle-east", recipes: ["Snack"], safety: "Nut allergy can be serious." },
  { slug: "macadamia", common: "Macadamia", latin: "Macadamia integrifolia", kind: "nut", origin: "Australia", region: "australia", recipes: ["Snack"], safety: "Nut allergy can be serious." },
  { slug: "brazil-nut", common: "Brazil nut", latin: "Bertholletia excelsa", kind: "nut", origin: "Amazon", region: "amazon", recipes: ["Snack"], safety: "Nut allergy can be serious. Selenium is high — a few nuts is plenty." },
  { slug: "chestnut", common: "Sweet chestnut", latin: "Castanea sativa", kind: "nut", origin: "Europe / West Asia", region: "mediterranean", recipes: ["Roast"] },
  { slug: "peanut", common: "Peanut", latin: "Arachis hypogaea", kind: "legume", origin: "South America", region: "andes", recipes: ["Roast", "Sauce"], safety: "Peanut allergy can be serious." },
  { slug: "lentil", common: "Lentil", latin: "Lens culinaris", kind: "legume", origin: "Fertile Crescent", region: "middle-east", recipes: ["Dhal", "Soup"] },
  { slug: "chickpea", common: "Chickpea", latin: "Cicer arietinum", kind: "legume", origin: "West Asia", region: "middle-east", recipes: ["Hummus", "Stew"] },
  { slug: "black-bean", common: "Black bean", latin: "Phaseolus vulgaris", kind: "legume", origin: "Americas", region: "mesoamerica", recipes: ["Stew", "Rice and peas variants"] },
  { slug: "kidney-bean", common: "Kidney bean", latin: "Phaseolus vulgaris", kind: "legume", origin: "Americas", region: "andes", recipes: ["Stew"], safety: "Red kidney beans must be boiled well. Never eat them raw or undercooked." },
  { slug: "soybean", common: "Soybean", latin: "Glycine max", kind: "legume", origin: "East Asia", region: "east-asia", recipes: ["Tofu", "Edamame"] },
  { slug: "pigeon-pea", common: "Pigeon pea / gungo", latin: "Cajanus cajan", kind: "legume", origin: "South Asia / Africa use", region: "caribbean", recipes: ["Rice and peas"] },

  { slug: "cinnamon", common: "Cinnamon", latin: "Cinnamomum verum", kind: "spice", origin: "Sri Lanka / South Asia", region: "south-asia", recipes: ["Baking", "Tea"] },
  { slug: "black-pepper", common: "Black pepper", latin: "Piper nigrum", kind: "spice", origin: "South India", region: "south-asia", recipes: ["Seasoning"] },
  { slug: "nutmeg", common: "Nutmeg", latin: "Myristica fragrans", kind: "spice", origin: "Maluku Islands", region: "southeast-asia", grow: ["Caribbean Grenada"], recipes: ["Baking"], safety: "Tiny cooking amounts only. Not a toy spice." },
  { slug: "clove", common: "Clove", latin: "Syzygium aromaticum", kind: "spice", origin: "Maluku Islands", region: "southeast-asia", recipes: ["Stew", "Baking"] },
  { slug: "vanilla", common: "Vanilla", latin: "Vanilla planifolia", kind: "spice", origin: "Mesoamerica", region: "mesoamerica", grow: ["Madagascar", "Caribbean"], recipes: ["Baking"] },
  { slug: "cardamom", common: "Cardamom", latin: "Elettaria cardamomum", kind: "spice", origin: "South India / Sri Lanka", region: "south-asia", recipes: ["Tea", "Baking"] },
  { slug: "cumin", common: "Cumin", latin: "Cuminum cyminum", kind: "spice", origin: "West Asia / Mediterranean", region: "middle-east", recipes: ["Stew"] },
  { slug: "cocoa-nibs", common: "Cocoa", latin: "Theobroma cacao", kind: "spice", origin: "Amazon / Mesoamerica", region: "amazon", recipes: ["Drink", "Chocolate"] },
  { slug: "allspice", common: "Allspice / pimento", latin: "Pimenta dioica", kind: "spice", origin: "Caribbean / Mesoamerica", region: "caribbean", recipes: ["Jerk seasoning", "Baking"] },
  { slug: "annatto", common: "Annatto / achiote", latin: "Bixa orellana", kind: "spice", origin: "Tropical Americas", region: "amazon", recipes: ["Colour", "Stew"] },

  { slug: "nettle", common: "Stinging nettle", latin: "Urtica dioica", kind: "wild", origin: "Europe and Asia", region: "britain", recipes: ["Cooked soup"], safety: "Pick and cook with an adult. Stings when raw." },
  { slug: "wild-garlic", common: "Wild garlic", latin: "Allium ursinum", kind: "wild", origin: "Europe", region: "britain", recipes: ["Pesto"], safety: "Must be identified by a knowledgeable adult. Lookalikes exist." },
  { slug: "rosehip", common: "Rosehip", latin: "Rosa canina", kind: "wild", origin: "Europe and West Asia", region: "britain", recipes: ["Syrup"], safety: "Remove itchy seeds. Adult prep." },
  { slug: "sea-grape", common: "Sea grape", latin: "Coccoloba uvifera", kind: "fruit", origin: "Caribbean coasts", region: "caribbean", recipes: ["Jelly"] },
  { slug: "june-plum", common: "June plum / golden apple", latin: "Spondias dulcis", kind: "fruit", origin: "Pacific / Southeast Asia", region: "caribbean", recipes: ["Fresh", "Juice"] },
  { slug: "otaheite-apple", common: "Otaheite apple", latin: "Syzygium malaccense", kind: "fruit", origin: "Southeast Asia / Pacific", region: "caribbean", recipes: ["Fresh fruit"] },
  { slug: "naseberry", common: "Naseberry", latin: "Manilkara zapota", kind: "fruit", origin: "Mesoamerica", region: "caribbean", recipes: ["Ripe fruit"] },
  { slug: "guinep", common: "Guinep / chenette", latin: "Melicoccus bijugatus", kind: "fruit", origin: "Tropical Americas", region: "caribbean", recipes: ["Fresh fruit"], safety: "Do not swallow the stone." },
  { slug: "sweetsop", common: "Sweetsop", latin: "Annona squamosa", kind: "fruit", origin: "Tropical Americas", region: "caribbean", recipes: ["Pulp"], safety: "Do not eat seeds." },
  { slug: "carambola", common: "Carambola", latin: "Averrhoa carambola", kind: "fruit", origin: "Southeast Asia", region: "caribbean", recipes: ["Slices"] },
  { slug: "okra-caribbean", common: "Lady’s finger okra", latin: "Abelmoschus esculentus", kind: "vegetable", origin: "Africa", region: "caribbean", recipes: ["Soup"] },
  { slug: "chocho", common: "Chocho / chayote", latin: "Sechium edule", kind: "vegetable", origin: "Mesoamerica", region: "caribbean", recipes: ["Boil", "Stew"] },
  { slug: "pumpkin-caribbean", common: "Caribbean pumpkin", latin: "Cucurbita moschata", kind: "vegetable", origin: "Americas", region: "caribbean", recipes: ["Soup"] },
  { slug: "scotch-bonnet", common: "Scotch bonnet", latin: "Capsicum chinense", kind: "spice", origin: "Amazon / Caribbean", region: "caribbean", recipes: ["Pepper sauce"], safety: "Very hot. Adult cooking. Keep off skin and eyes." },
  { slug: "breadfruit-roasted", common: "Breadfruit (roast)", latin: "Artocarpus altilis", kind: "fruit", origin: "Pacific", region: "caribbean", recipes: ["Roast", "Oil-down"] },
  { slug: "ackee-relative-note", common: "Blighia (ackee family teaching record)", latin: "Blighia sapida", kind: "fruit", origin: "West Africa", region: "west-africa", recipes: ["Only ripe arils, cooked"], safety: "Unripe ackee is dangerous. Only adults prepare known ripe fruit." },

  { slug: "kale-sea", common: "Sea kale", latin: "Crambe maritima", kind: "wild", origin: "Atlantic Europe", region: "britain", recipes: ["Blanched shoots"], safety: "Forage only with an expert adult." },
  { slug: "samphire", common: "Marsh samphire", latin: "Salicornia europaea", kind: "wild", origin: "Europe coasts", region: "britain", recipes: ["Steam"], safety: "Forage only where clean and allowed." },
  { slug: "sorrel-hibiscus", common: "Sorrel / roselle", latin: "Hibiscus sabdariffa", kind: "herb", origin: "Africa", region: "west-africa", grow: ["Caribbean drinks"], recipes: ["Holiday drink"] },
  { slug: "baobab", common: "Baobab", latin: "Adansonia digitata", kind: "fruit", origin: "Africa", region: "west-africa", recipes: ["Pulp drink"] },
  { slug: "shea", common: "Shea", latin: "Vitellaria paradoxa", kind: "nut", origin: "West Africa", region: "west-africa", recipes: ["Butter"], safety: "Food and skin-care plant. Not a medicine claim." },
  { slug: "enset", common: "Enset", latin: "Ensete ventricosum", kind: "vegetable", origin: "Ethiopia", region: "horn-of-africa", recipes: ["Fermented staple"] },
  { slug: "teff-injera", common: "Teff (injera grain)", latin: "Eragrostis tef", kind: "grain", origin: "Ethiopian highlands", region: "horn-of-africa", recipes: ["Injera"] },
  { slug: "coffee", common: "Coffee cherry", latin: "Coffea arabica", kind: "fruit", origin: "Ethiopia", region: "horn-of-africa", recipes: ["Roasted bean drink"], safety: "Adult drink. Not for little children." },
  { slug: "tea-camellia", common: "Tea", latin: "Camellia sinensis", kind: "herb", origin: "East Asia", region: "east-asia", recipes: ["Infusion"], safety: "Caffeine. Gentle for children if at all." },
  { slug: "sesame", common: "Sesame", latin: "Sesamum indicum", kind: "legume", origin: "Africa / India", region: "horn-of-africa", recipes: ["Paste", "Seed"], safety: "Sesame allergy can be serious." },
  { slug: "sunflower-seed", common: "Sunflower seed", latin: "Helianthus annuus", kind: "nut", origin: "North America", region: "north-america", recipes: ["Snack"] },
  { slug: "pumpkin-seed", common: "Pumpkin seed", latin: "Cucurbita pepo", kind: "nut", origin: "Americas", region: "mesoamerica", recipes: ["Roast"] },
  { slug: "linseed", common: "Linseed / flax", latin: "Linum usitatissimum", kind: "grain", origin: "Fertile Crescent", region: "middle-east", recipes: ["Seed on bread"] },
  { slug: "hemp-seed", common: "Hemp seed (food)", latin: "Cannabis sativa (food seed)", kind: "nut", origin: "Central Asia", region: "central-asia", recipes: ["Seed"], safety: "Food seed only. This is not a drugs page." },
  { slug: "mustard", common: "Mustard", latin: "Brassica juncea / Sinapis alba", kind: "spice", origin: "Europe / Asia", region: "south-asia", recipes: ["Seed", "Greens"] },
  { slug: "horseradish", common: "Horseradish", latin: "Armoracia rusticana", kind: "spice", origin: "Europe", region: "britain", recipes: ["Sauce"], safety: "Very strong. Tiny amounts." },
  { slug: "wasabi", common: "Wasabi", latin: "Eutrema japonicum", kind: "spice", origin: "Japan", region: "east-asia", recipes: ["Paste"], safety: "Very strong." },
  { slug: "nori-note", common: "Nori (sea laver teaching record)", latin: "Pyropia / Porphyra spp.", kind: "wild", origin: "East Asia coasts", region: "east-asia", recipes: ["Sheets"], safety: "Seaweed is not a land fruit. Adult kitchen food." },
];

function expand(s: Seed): PlantRecord {
  const q = encodeURIComponent(s.latin.split("/")[0].trim());
  return {
    slug: s.slug,
    commonName: s.common,
    scientificName: s.latin,
    kind: s.kind,
    indigenousAndHistoricalNames: s.names ?? [],
    botanicalOrigin: s.origin,
    presentGrowingRegions: s.grow ?? [s.origin, "Gardens and farms worldwide where climate fits"],
    climate: "Varies by variety. Grown where the season matches the crop.",
    soilRequirements: "Most food crops like loose, living soil with organic matter. Wetland crops are the exception.",
    seedAndGrowingCycle: "Grown from seed, tuber, cutting or sucker depending on the plant. Ask a local grower for the way used here.",
    seasons: "Follows local rains and day length. Shops can hide the true season with storage and travel.",
    growersAndCommunities: "Home gardens, small farms and, for some crops, large farms far from the kitchen.",
    harvestingMethod: "Pick, dig or cut when the crop is ready. An adult should show the safe way.",
    farmToFamily: "Short when grown nearby. Longer when shipped across oceans.",
    transportAndFoodMiles: "Count the journey: garden, market, or a ship. Near food usually uses less travel.",
    traditionalRecipes: s.recipes ?? ["Cooked as food with a trusted adult"],
    culturalHistory: `${s.common} is part of kitchens in its home region and in places people carried it.`,
    historicalMovement: "People, trade and gardens moved this crop. Botanical origin is not the same as every place it grows today.",
    nutrition: "Food, not medicine. What is in it changes with variety, soil and cooking.",
    safetyAndAllergies:
      s.safety ??
      "Eat known food plants from a trusted grown-up. Never eat a wild lookalike from a photo alone.",
    languages: [
      { language: "English", name: s.common },
      ...(s.names ?? []).slice(0, 1).map((n) => ({ language: "Other common name", name: n })),
    ],
    mapRegion: s.region === "east-africa-fallback" ? "horn-of-africa" : s.region,
    relatedSongs: ["everything-is-connected"],
    relatedEpisodes: ["wake-up-little-seed"],
    editorialStatus: "in_review",
    claims: [
      {
        id: `${s.slug}-name`,
        text: `${s.latin} is the scientific name used here for ${s.common}.`,
        category: "botany",
        evidence: "plausible",
        editorialStatus: "in_review",
        sources: [
          {
            title: s.latin,
            publisher: "Royal Botanic Gardens, Kew — Plants of the World Online (search)",
            url: `https://powo.science.kew.org/results?q=${q}`,
            accessed: "2026-09-14",
            notes: "Look up the accepted name. Catalogue records wait for editor review.",
          },
        ],
      },
    ],
  };
}

export const catalogPlants: PlantRecord[] = SEEDS.map(expand);
