/**
 * Initial ~50 plant seed dataset
 * Caribbean, African heritage, British wild, and globally familiar plants
 * All traditional uses are labelled as such — never presented as clinical fact.
 */

export const seedPlants = [
  // ——— Caribbean / Tropical ———
  {
    slug: "soursop",
    common_name: "Soursop",
    scientific_name: "Annona muricata",
    other_names: ["Guanábana", "Graviola"],
    plant_family: "Annonaceae",
    native_region: ["Tropical Americas", "Caribbean"],
    current_distribution: ["Tropics worldwide"],
    description: "A large, spiky green fruit with soft white flesh and a unique sweet-tart flavour.",
    growth_habit: "Evergreen tree",
    edible_parts: ["fruit pulp"],
    traditional_uses: "Fruit eaten fresh or in drinks; leaves used in traditional herbal preparations in some cultures.",
    documented_nutrients: { vitamin_c: "present", fiber: "present" },
    warnings: "Seeds are not eaten. Always consult reliable sources before using any plant medicinally.",
    toxic_parts: ["seeds"],
    allergens: [],
    historical_notes: "Cultivated across the Caribbean and tropical Americas for centuries.",
    cultural_notes: "Popular in Caribbean juices, ice creams and desserts.",
    verification_status: "good_evidence" as const
  },
  {
    slug: "banana",
    common_name: "Banana",
    scientific_name: "Musa acuminata / Musa balbisiana hybrids",
    other_names: ["Plantain (related)"],
    plant_family: "Musaceae",
    native_region: ["Southeast Asia", "Papua New Guinea"],
    current_distribution: ["Tropics and subtropics worldwide"],
    description: "Elongated yellow fruit that grows in bunches. One of the world’s most important food crops.",
    growth_habit: "Herbaceous perennial (not a true tree)",
    edible_parts: ["fruit"],
    traditional_uses: "Eaten ripe or cooked; leaves used as food wrappers in many cultures.",
    documented_nutrients: { potassium: "high", vitamin_b6: "present", vitamin_c: "present" },
    warnings: "None for normal consumption of the fruit.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Domesticated thousands of years ago in Southeast Asia; reached Africa and the Americas via trade and colonial routes.",
    cultural_notes: "Central to diets and economies across the tropics.",
    verification_status: "verified" as const
  },
  {
    slug: "plantain",
    common_name: "Plantain",
    scientific_name: "Musa paradisiaca",
    other_names: ["Cooking banana"],
    plant_family: "Musaceae",
    native_region: ["Southeast Asia"],
    current_distribution: ["Tropics worldwide"],
    description: "Starchier relative of the sweet banana, usually cooked before eating.",
    growth_habit: "Herbaceous perennial",
    edible_parts: ["fruit (cooked)"],
    traditional_uses: "Boiled, fried, roasted or mashed in Caribbean, African and Latin American cuisines.",
    documented_nutrients: { carbohydrates: "high", potassium: "high" },
    warnings: "Typically eaten cooked.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Spread widely with African and Caribbean food cultures.",
    cultural_notes: "Staple in many Caribbean and West African dishes.",
    verification_status: "verified" as const
  },
  {
    slug: "mango",
    common_name: "Mango",
    scientific_name: "Mangifera indica",
    other_names: ["Manga"],
    plant_family: "Anacardiaceae",
    native_region: ["South Asia"],
    current_distribution: ["Tropics and subtropics worldwide"],
    description: "Sweet, juicy stone fruit with a large flat seed. Hundreds of cultivars exist.",
    growth_habit: "Evergreen tree",
    edible_parts: ["fruit pulp"],
    traditional_uses: "Eaten fresh, dried, pickled or in chutneys; leaves and other parts used in some traditional practices.",
    documented_nutrients: { vitamin_a: "present", vitamin_c: "present", fiber: "present" },
    warnings: "Some people are sensitive to the skin or sap (related to poison ivy family).",
    toxic_parts: [],
    allergens: ["possible cross-reactivity with cashew/pistachio family"],
    historical_notes: "Cultivated in India for thousands of years; spread by traders and colonial networks.",
    cultural_notes: "National fruit of India, Pakistan and the Philippines; deeply woven into Caribbean life.",
    verification_status: "verified" as const
  },
  {
    slug: "pineapple",
    common_name: "Pineapple",
    scientific_name: "Ananas comosus",
    other_names: ["Ananas"],
    plant_family: "Bromeliaceae",
    native_region: ["South America (Paraguay/Brazil region)"],
    current_distribution: ["Tropics worldwide"],
    description: "Multiple fruit formed from fused berries, with a spiky crown of leaves.",
    growth_habit: "Herbaceous perennial",
    edible_parts: ["fruit"],
    traditional_uses: "Eaten fresh or cooked; historically used as a symbol of hospitality.",
    documented_nutrients: { vitamin_c: "high", manganese: "present", bromelain: "enzyme present" },
    warnings: "Bromelain can irritate the mouth if large quantities are eaten.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Domesticated by Indigenous peoples of South America; carried to the Caribbean and beyond by Europeans.",
    cultural_notes: "Icon of welcome; major crop in many tropical islands.",
    verification_status: "verified" as const
  },
  {
    slug: "coconut",
    common_name: "Coconut",
    scientific_name: "Cocos nucifera",
    other_names: ["Coco"],
    plant_family: "Arecaceae",
    native_region: ["Tropical Indo-Pacific (debated exact origin)"],
    current_distribution: ["Tropical coasts worldwide"],
    description: "Large hard-shelled fruit of the coconut palm, providing water, meat, oil and fibre.",
    growth_habit: "Palm tree",
    edible_parts: ["water", "meat", "oil"],
    traditional_uses: "Food, drink, oil, fibre, building material — one of the most useful plants on Earth.",
    documented_nutrients: { medium_chain_triglycerides: "present", manganese: "present" },
    warnings: "Falling coconuts can be dangerous under trees.",
    toxic_parts: [],
    allergens: ["rare coconut allergy"],
    historical_notes: "Spread by ocean currents and human voyaging across the tropics.",
    cultural_notes: "Central to many Pacific, Asian, African and Caribbean cultures.",
    verification_status: "verified" as const
  },
  {
    slug: "guava",
    common_name: "Guava",
    scientific_name: "Psidium guajava",
    other_names: ["Guayaba"],
    plant_family: "Myrtaceae",
    native_region: ["Tropical Americas"],
    current_distribution: ["Tropics worldwide"],
    description: "Fragrant fruit with pink or white flesh and many small hard seeds.",
    growth_habit: "Shrub or small tree",
    edible_parts: ["fruit"],
    traditional_uses: "Eaten fresh or in jams; leaves used in some traditional preparations.",
    documented_nutrients: { vitamin_c: "very high", fiber: "high" },
    warnings: "None for normal fruit consumption.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Native to the Americas; spread widely after European contact.",
    cultural_notes: "Common in Caribbean gardens and markets.",
    verification_status: "verified" as const
  },
  {
    slug: "ackee",
    common_name: "Ackee",
    scientific_name: "Blighia sapida",
    other_names: ["Akee"],
    plant_family: "Sapindaceae",
    native_region: ["West Africa"],
    current_distribution: ["Caribbean (especially Jamaica)", "West Africa"],
    description: "Fruit that opens when ripe to reveal creamy yellow arils. Jamaica’s national fruit.",
    growth_habit: "Tree",
    edible_parts: ["ripe arils only"],
    traditional_uses: "Cooked with saltfish in the national dish of Jamaica.",
    documented_nutrients: { protein: "present", fats: "present" },
    warnings: "UNRIPE arils and the pink membrane are toxic (hypoglycin). Only eat fully opened, ripe arils prepared by knowledgeable cooks.",
    toxic_parts: ["unripe arils", "seeds", "pink membrane"],
    allergens: [],
    historical_notes: "Brought from West Africa to the Caribbean during the colonial period.",
    cultural_notes: "Central to Jamaican identity and cuisine.",
    verification_status: "verified" as const
  },
  {
    slug: "breadfruit",
    common_name: "Breadfruit",
    scientific_name: "Artocarpus altilis",
    other_names: ["Ulu"],
    plant_family: "Moraceae",
    native_region: ["New Guinea / Pacific"],
    current_distribution: ["Tropical Pacific", "Caribbean", "tropics"],
    description: "Large starchy fruit that can be roasted, boiled or fried — historically a voyage food.",
    growth_habit: "Tree",
    edible_parts: ["fruit (cooked)"],
    traditional_uses: "Staple carbohydrate in Pacific and Caribbean diets.",
    documented_nutrients: { carbohydrates: "high", fiber: "present" },
    warnings: "Usually eaten cooked.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Famous for the HMS Bounty voyage that attempted to transplant it to the Caribbean as slave food.",
    cultural_notes: "Important in Pacific Islander and Caribbean food cultures.",
    verification_status: "verified" as const
  },
  {
    slug: "tamarind",
    common_name: "Tamarind",
    scientific_name: "Tamarindus indica",
    other_names: ["Tamarindo"],
    plant_family: "Fabaceae",
    native_region: ["Africa (likely)"],
    current_distribution: ["Tropics worldwide"],
    description: "Pod fruit with sticky sweet-sour pulp around hard seeds.",
    growth_habit: "Tree",
    edible_parts: ["pulp"],
    traditional_uses: "Drinks, sauces, sweets; used in many traditional cuisines.",
    documented_nutrients: { vitamin_c: "present", tartaric_acid: "present" },
    warnings: "None for normal culinary use.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Spread from Africa through trade to Asia and the Americas.",
    cultural_notes: "Key flavour in Caribbean, Latin American, Indian and African cooking.",
    verification_status: "verified" as const
  },
  {
    slug: "papaya",
    common_name: "Papaya",
    scientific_name: "Carica papaya",
    other_names: ["Pawpaw"],
    plant_family: "Caricaceae",
    native_region: ["Central America / southern Mexico"],
    current_distribution: ["Tropics worldwide"],
    description: "Large orange-fleshed fruit with black seeds in a central cavity.",
    growth_habit: "Herbaceous tree-like plant",
    edible_parts: ["fruit", "seeds (in moderation)"],
    traditional_uses: "Eaten fresh; green fruit cooked as vegetable; latex used traditionally in some places.",
    documented_nutrients: { vitamin_c: "high", vitamin_a: "present", papain: "enzyme" },
    warnings: "Latex can irritate skin. Unripe fruit and latex not for unrestricted use.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Domesticated in the Americas; spread rapidly after contact.",
    cultural_notes: "Everyday fruit across the tropics.",
    verification_status: "verified" as const
  },
  {
    slug: "passion-fruit",
    common_name: "Passion Fruit",
    scientific_name: "Passiflora edulis",
    other_names: ["Passionfruit", "Granadilla"],
    plant_family: "Passifloraceae",
    native_region: ["South America"],
    current_distribution: ["Tropics and subtropics"],
    description: "Purple or yellow fruit with aromatic seedy pulp.",
    growth_habit: "Vine",
    edible_parts: ["pulp and seeds"],
    traditional_uses: "Eaten fresh, in drinks and desserts.",
    documented_nutrients: { vitamin_c: "present", fiber: "present" },
    warnings: "None for normal consumption.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Name linked to Christian symbolism by European missionaries; native to South America.",
    cultural_notes: "Popular in Caribbean and tropical drinks.",
    verification_status: "verified" as const
  },
  {
    slug: "avocado",
    common_name: "Avocado",
    scientific_name: "Persea americana",
    other_names: ["Alligator pear"],
    plant_family: "Lauraceae",
    native_region: ["Central America / Mexico"],
    current_distribution: ["Subtropics and tropics worldwide"],
    description: "Creamy green-fleshed fruit with a large central stone.",
    growth_habit: "Tree",
    edible_parts: ["flesh"],
    traditional_uses: "Eaten fresh, in salads, spreads and traditional dishes.",
    documented_nutrients: { monounsaturated_fat: "high", potassium: "high", fiber: "present" },
    warnings: "Leaves and pit of some varieties can be toxic to animals.",
    toxic_parts: ["leaves (some varieties)", "pit (for pets)"],
    allergens: ["possible latex-fruit syndrome"],
    historical_notes: "Cultivated by Mesoamerican peoples for thousands of years.",
    cultural_notes: "Now a global staple; important in Latin American and Caribbean diets.",
    verification_status: "verified" as const
  },
  {
    slug: "cacao",
    common_name: "Cacao",
    scientific_name: "Theobroma cacao",
    other_names: ["Cocoa"],
    plant_family: "Malvaceae",
    native_region: ["Amazon basin / Central America"],
    current_distribution: ["Tropical Americas", "West Africa", "Southeast Asia"],
    description: "Pods containing bitter seeds that are fermented and processed into chocolate.",
    growth_habit: "Understory tree",
    edible_parts: ["processed seeds (cocoa/chocolate)"],
    traditional_uses: "Sacred drink of Mesoamerican cultures; now global chocolate industry.",
    documented_nutrients: { flavonoids: "present", theobromine: "present", magnesium: "present" },
    warnings: "Raw cacao is bitter; processed chocolate often high in sugar.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Used by Olmec, Maya and Aztec civilisations; taken to Europe after conquest.",
    cultural_notes: "One of the most culturally and economically important plants in history.",
    verification_status: "verified" as const
  },
  {
    slug: "june-plum",
    common_name: "June Plum",
    scientific_name: "Spondias dulcis",
    other_names: ["Golden apple", "Ambarella"],
    plant_family: "Anacardiaceae",
    native_region: ["Melanesia / Polynesia"],
    current_distribution: ["Caribbean", "tropics"],
    description: "Crisp, tart-sweet fruit often eaten green with salt or pepper.",
    growth_habit: "Tree",
    edible_parts: ["fruit"],
    traditional_uses: "Eaten fresh, pickled or in drinks.",
    documented_nutrients: { vitamin_c: "present" },
    warnings: "None for normal consumption.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Introduced to the Caribbean and widely naturalised.",
    cultural_notes: "Popular street snack in the Caribbean.",
    verification_status: "good_evidence" as const
  },
  {
    slug: "naseberry",
    common_name: "Naseberry",
    scientific_name: "Manilkara zapota",
    other_names: ["Sapodilla", "Chicle"],
    plant_family: "Sapotaceae",
    native_region: ["Central America / Mexico"],
    current_distribution: ["Tropics"],
    description: "Brown-skinned fruit with sweet, grainy, malty flesh.",
    growth_habit: "Tree",
    edible_parts: ["fruit"],
    traditional_uses: "Eaten fresh; latex historically used for chicle (chewing gum).",
    documented_nutrients: { sugars: "high", fiber: "present" },
    warnings: "Seeds are not eaten.",
    toxic_parts: ["seeds"],
    allergens: [],
    historical_notes: "Ancient Mesoamerican crop; latex used by Maya.",
    cultural_notes: "Beloved Caribbean fruit.",
    verification_status: "verified" as const
  },
  {
    slug: "sweetsop",
    common_name: "Sweetsop",
    scientific_name: "Annona squamosa",
    other_names: ["Sugar apple", "Custard apple (sometimes)"],
    plant_family: "Annonaceae",
    native_region: ["Tropical Americas"],
    current_distribution: ["Tropics"],
    description: "Knobbly green fruit that segments easily, with sweet creamy flesh.",
    growth_habit: "Small tree",
    edible_parts: ["fruit pulp"],
    traditional_uses: "Eaten fresh.",
    documented_nutrients: { vitamin_c: "present", sugars: "high" },
    warnings: "Seeds are toxic if crushed and ingested.",
    toxic_parts: ["seeds"],
    allergens: [],
    historical_notes: "Related to soursop and cherimoya; long cultivated in the Americas.",
    cultural_notes: "Common backyard fruit in the Caribbean.",
    verification_status: "verified" as const
  },
  {
    slug: "starfruit",
    common_name: "Starfruit",
    scientific_name: "Averrhoa carambola",
    other_names: ["Carambola"],
    plant_family: "Oxalidaceae",
    native_region: ["Southeast Asia"],
    current_distribution: ["Tropics"],
    description: "Yellow fruit that forms a star shape when sliced.",
    growth_habit: "Tree",
    edible_parts: ["fruit"],
    traditional_uses: "Eaten fresh or in salads.",
    documented_nutrients: { vitamin_c: "present", oxalic_acid: "present" },
    warnings: "High oxalate content — people with kidney issues should be cautious.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Southeast Asian origin; now grown in many tropical regions including the Caribbean.",
    cultural_notes: "Popular for its star shape and mild flavour.",
    verification_status: "verified" as const
  },
  {
    slug: "jackfruit",
    common_name: "Jackfruit",
    scientific_name: "Artocarpus heterophyllus",
    other_names: ["Jakfruit"],
    plant_family: "Moraceae",
    native_region: ["South / Southeast Asia"],
    current_distribution: ["Tropics"],
    description: "Largest tree-borne fruit; flesh can be sweet or used as savoury meat substitute when unripe.",
    growth_habit: "Tree",
    edible_parts: ["arils", "seeds (cooked)"],
    traditional_uses: "Eaten ripe as fruit or unripe as vegetable; seeds roasted or boiled.",
    documented_nutrients: { carbohydrates: "high", fiber: "high" },
    warnings: "Latex can be sticky; prepare with oil on hands/tools.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Ancient Asian crop; now grown in many tropical countries.",
    cultural_notes: "Growing global interest as plant-based meat alternative.",
    verification_status: "verified" as const
  },
  {
    slug: "callaloo",
    common_name: "Callaloo",
    scientific_name: "Amaranthus spp. / Xanthosoma (varies by region)",
    other_names: ["Amaranth greens", "Dasheen leaves (some regions)"],
    plant_family: "Amaranthaceae / Araceae",
    native_region: ["Americas / Africa (species dependent)"],
    current_distribution: ["Caribbean", "Africa", "tropics"],
    description: "Leafy green used as a vegetable; exact plant varies by island and country.",
    growth_habit: "Herbaceous",
    edible_parts: ["leaves (cooked)"],
    traditional_uses: "Cooked as a spinach-like green; central to Caribbean ‘callaloo’ dishes.",
    documented_nutrients: { iron: "present", vitamin_a: "present", calcium: "present" },
    warnings: "Some species require thorough cooking; identification matters.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Name and dish reflect African and Indigenous Caribbean foodways.",
    cultural_notes: "Staple green vegetable across the Caribbean.",
    verification_status: "good_evidence" as const
  },

  // ——— African heritage crops ———
  {
    slug: "yam",
    common_name: "Yam",
    scientific_name: "Dioscorea spp.",
    other_names: ["True yam"],
    plant_family: "Dioscoreaceae",
    native_region: ["West Africa", "Asia", "Americas (different species)"],
    current_distribution: ["Tropics"],
    description: "Starchy tubers; West African species are culturally central.",
    growth_habit: "Climbing vine",
    edible_parts: ["tuber (cooked)"],
    traditional_uses: "Boiled, pounded, fried — foundation of many West African and Caribbean dishes.",
    documented_nutrients: { carbohydrates: "high", potassium: "present" },
    warnings: "Some wild species are toxic; only cultivated food yams should be eaten.",
    toxic_parts: ["some wild species"],
    allergens: [],
    historical_notes: "Domestication in West Africa is ancient; carried to the Caribbean via the transatlantic trade.",
    cultural_notes: "Deeply important in West African and Caribbean food cultures.",
    verification_status: "verified" as const
  },
  {
    slug: "cassava",
    common_name: "Cassava",
    scientific_name: "Manihot esculenta",
    other_names: ["Yuca", "Manioc", "Tapioca"],
    plant_family: "Euphorbiaceae",
    native_region: ["South America"],
    current_distribution: ["Tropics worldwide"],
    description: "Starchy root that must be properly prepared; source of tapioca.",
    growth_habit: "Shrub",
    edible_parts: ["root (properly prepared)", "leaves (cooked, some varieties)"],
    traditional_uses: "Flour, flatbreads, fufu, tapioca; critical calorie crop.",
    documented_nutrients: { carbohydrates: "very high" },
    warnings: "Contains cyanogenic glycosides. Bitter varieties must be thoroughly processed (soaking, fermenting, cooking). Never eat raw bitter cassava.",
    toxic_parts: ["raw bitter root"],
    allergens: [],
    historical_notes: "Domesticated in South America; became a staple across Africa after introduction.",
    cultural_notes: "One of the world’s most important tropical food crops.",
    verification_status: "verified" as const
  },
  {
    slug: "sorghum",
    common_name: "Sorghum",
    scientific_name: "Sorghum bicolor",
    other_names: ["Great millet", "Guinea corn"],
    plant_family: "Poaceae",
    native_region: ["Africa"],
    current_distribution: ["Africa", "Asia", "Americas"],
    description: "Drought-tolerant cereal grain.",
    growth_habit: "Annual grass",
    edible_parts: ["grain"],
    traditional_uses: "Porridge, flatbreads, fermented drinks, animal feed.",
    documented_nutrients: { carbohydrates: "high", protein: "present", fiber: "present" },
    warnings: "None for normal food use.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "One of Africa’s ancient domesticated grains; still vital for food security.",
    cultural_notes: "Foundational to many African food systems.",
    verification_status: "verified" as const
  },
  {
    slug: "millet",
    common_name: "Millet",
    scientific_name: "Various (Pennisetum, Eleusine, etc.)",
    other_names: ["Pearl millet", "Finger millet"],
    plant_family: "Poaceae",
    native_region: ["Africa", "Asia"],
    current_distribution: ["Semi-arid tropics"],
    description: "Group of small-seeded grasses valued for drought tolerance.",
    growth_habit: "Annual grass",
    edible_parts: ["grain"],
    traditional_uses: "Porridge, flatbreads, fermented foods.",
    documented_nutrients: { carbohydrates: "high", minerals: "present" },
    warnings: "None for normal food use.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Among the earliest domesticated African crops.",
    cultural_notes: "Critical for food security in dry regions.",
    verification_status: "verified" as const
  },
  {
    slug: "fonio",
    common_name: "Fonio",
    scientific_name: "Digitaria exilis",
    other_names: ["Acha"],
    plant_family: "Poaceae",
    native_region: ["West Africa"],
    current_distribution: ["West Africa"],
    description: "Tiny, fast-growing ancient grain.",
    growth_habit: "Annual grass",
    edible_parts: ["grain"],
    traditional_uses: "Couscous-like dishes, porridge.",
    documented_nutrients: { amino_acids: "good profile", minerals: "present" },
    warnings: "None for normal food use.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "One of Africa’s oldest cultivated cereals; currently seeing global interest.",
    cultural_notes: "Sacred and everyday food in parts of West Africa.",
    verification_status: "good_evidence" as const
  },
  {
    slug: "teff",
    common_name: "Teff",
    scientific_name: "Eragrostis tef",
    other_names: [],
    plant_family: "Poaceae",
    native_region: ["Ethiopia / Eritrea"],
    current_distribution: ["Horn of Africa", "growing globally"],
    description: "Minute grain used to make injera.",
    growth_habit: "Annual grass",
    edible_parts: ["grain"],
    traditional_uses: "Injera flatbread, porridge.",
    documented_nutrients: { iron: "present", protein: "present", fiber: "present" },
    warnings: "None for normal food use.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Domesticated in the Ethiopian highlands; foundation of Ethiopian and Eritrean cuisine.",
    cultural_notes: "Central to the food culture of the Horn of Africa.",
    verification_status: "verified" as const
  },
  {
    slug: "okra",
    common_name: "Okra",
    scientific_name: "Abelmoschus esculentus",
    other_names: ["Ladies’ fingers", "Ochro"],
    plant_family: "Malvaceae",
    native_region: ["Africa (likely)"],
    current_distribution: ["Tropics and warm regions"],
    description: "Green pods with mucilaginous texture when cooked.",
    growth_habit: "Annual herb",
    edible_parts: ["pods"],
    traditional_uses: "Stews, soups, fried; thickens dishes naturally.",
    documented_nutrients: { fiber: "present", vitamin_c: "present", folate: "present" },
    warnings: "None for normal consumption.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "African origin; became important in Southern US, Caribbean and global cuisines.",
    cultural_notes: "Key ingredient in many African-diaspora dishes including gumbo and Caribbean stews.",
    verification_status: "verified" as const
  },
  {
    slug: "black-eyed-pea",
    common_name: "Black-eyed Pea",
    scientific_name: "Vigna unguiculata",
    other_names: ["Cowpea"],
    plant_family: "Fabaceae",
    native_region: ["Africa"],
    current_distribution: ["Tropics and warm regions"],
    description: "Cream-coloured bean with a distinctive black hilum.",
    growth_habit: "Annual legume",
    edible_parts: ["seeds", "young pods", "leaves (in some traditions)"],
    traditional_uses: "Boiled, in stews, rice and peas, hoppin’ john.",
    documented_nutrients: { protein: "high", fiber: "high", folate: "present" },
    warnings: "None for normal consumption.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "African domesticate; carried to the Americas and became a diaspora staple.",
    cultural_notes: "Symbol of good luck in some New Year traditions; core to African-American and Caribbean cooking.",
    verification_status: "verified" as const
  },

  // ——— British / temperate wild & food plants ———
  {
    slug: "dandelion",
    common_name: "Dandelion",
    scientific_name: "Taraxacum officinale",
    other_names: ["Lion’s tooth"],
    plant_family: "Asteraceae",
    native_region: ["Eurasia"],
    current_distribution: ["Worldwide temperate"],
    description: "Familiar yellow flower that becomes a seed clock. Leaves, flowers and roots have long traditional uses.",
    growth_habit: "Perennial herb",
    edible_parts: ["young leaves", "flowers", "roasted roots (traditional)"],
    traditional_uses: "Salad greens, tea, traditional herbal use for various purposes.",
    documented_nutrients: { vitamin_a: "present", vitamin_k: "present", iron: "present" },
    warnings: "Never forage unless positively identified by a knowledgeable adult. Avoid plants from sprayed areas or polluted ground.",
    toxic_parts: [],
    allergens: ["possible Asteraceae sensitivity"],
    historical_notes: "Used in European traditional medicine and food for centuries.",
    cultural_notes: "Often dismissed as a weed, yet highly nutritious and resilient — a core Fruits Crew message.",
    verification_status: "good_evidence" as const
  },
  {
    slug: "nettle",
    common_name: "Stinging Nettle",
    scientific_name: "Urtica dioica",
    other_names: ["Nettle"],
    plant_family: "Urticaceae",
    native_region: ["Eurasia"],
    current_distribution: ["Temperate regions"],
    description: "Tall plant with stinging hairs; leaves become edible when cooked.",
    growth_habit: "Perennial herb",
    edible_parts: ["young leaves (cooked or dried)"],
    traditional_uses: "Soup, tea, traditional herbal use; historically used for fibre.",
    documented_nutrients: { iron: "present", calcium: "present", vitamin_a: "present" },
    warnings: "Stings when raw. Never forage without expert identification and adult supervision. Cook thoroughly.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Long history of food and fibre use in Europe.",
    cultural_notes: "Classic British wild edible when properly prepared.",
    verification_status: "good_evidence" as const
  },
  {
    slug: "wild-garlic",
    common_name: "Wild Garlic",
    scientific_name: "Allium ursinum",
    other_names: ["Ramsons"],
    plant_family: "Amaryllidaceae",
    native_region: ["Europe", "Asia"],
    current_distribution: ["European woodlands"],
    description: "Broad leaves with strong garlic scent; white starry flowers.",
    growth_habit: "Perennial bulb",
    edible_parts: ["leaves", "flowers"],
    traditional_uses: "Pesto, soups, salads — classic spring wild food.",
    documented_nutrients: { similar_to_garlic: "alliin compounds" },
    warnings: "Must be correctly identified — some lookalikes are toxic (e.g. lily of the valley). Adult expert identification required. Never forage alone as a child.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Traditional European woodland food plant.",
    cultural_notes: "Beloved sign of British spring.",
    verification_status: "good_evidence" as const
  },
  {
    slug: "blackberry",
    common_name: "Blackberry",
    scientific_name: "Rubus fruticosus agg.",
    other_names: ["Bramble"],
    plant_family: "Rosaceae",
    native_region: ["Europe", "Asia"],
    current_distribution: ["Temperate regions"],
    description: "Thorny scrambling shrub with dark sweet berries.",
    growth_habit: "Shrub / scrambler",
    edible_parts: ["fruit"],
    traditional_uses: "Eaten fresh, in jams, pies and syrups.",
    documented_nutrients: { vitamin_c: "present", fiber: "present", antioxidants: "present" },
    warnings: "Thorns. Pick from clean areas only.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Gathered for millennia across Europe.",
    cultural_notes: "Classic British late-summer forage (with adult supervision).",
    verification_status: "verified" as const
  },
  {
    slug: "elder",
    common_name: "Elder",
    scientific_name: "Sambucus nigra",
    other_names: ["Elderflower", "Elderberry"],
    plant_family: "Adoxaceae",
    native_region: ["Europe"],
    current_distribution: ["Temperate Europe and beyond"],
    description: "Shrub or small tree with fragrant cream flowers and dark berries.",
    growth_habit: "Shrub / small tree",
    edible_parts: ["flowers (cooked/processed)", "ripe berries (cooked)"],
    traditional_uses: "Elderflower cordial, fritters; elderberry syrups in traditional use.",
    documented_nutrients: { vitamin_c: "present in berries" },
    warnings: "Raw berries and other parts can cause nausea. Flowers and berries should be properly prepared. Expert identification required.",
    toxic_parts: ["raw berries (can upset stomach)", "leaves", "stems"],
    allergens: [],
    historical_notes: "Deep folklore and traditional use across Europe.",
    cultural_notes: "Elderflower is a celebrated British summer flavour.",
    verification_status: "good_evidence" as const
  },
  {
    slug: "hawthorn",
    common_name: "Hawthorn",
    scientific_name: "Crataegus monogyna",
    other_names: ["May tree", "Quickthorn"],
    plant_family: "Rosaceae",
    native_region: ["Europe"],
    current_distribution: ["Europe", "naturalised elsewhere"],
    description: "Thorny hedgerow tree with white May blossom and red haws.",
    growth_habit: "Tree / shrub",
    edible_parts: ["haws (processed)", "young leaves (traditional)"],
    traditional_uses: "Haws in jellies and traditional preparations; blossom in folklore.",
    documented_nutrients: {},
    warnings: "Identification important. Traditional medicinal claims require careful evidence review.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Ancient hedgerow plant of Britain and Europe; rich folklore.",
    cultural_notes: "Symbol of British countryside and May traditions.",
    verification_status: "good_evidence" as const
  },
  {
    slug: "rosehip",
    common_name: "Rosehip",
    scientific_name: "Rosa canina (and other Rosa spp.)",
    other_names: ["Dog rose hips"],
    plant_family: "Rosaceae",
    native_region: ["Europe", "Asia"],
    current_distribution: ["Temperate regions"],
    description: "Bright red or orange fruit of wild roses.",
    growth_habit: "Shrub",
    edible_parts: ["hips (processed, seeds removed)"],
    traditional_uses: "Syrups, teas, traditional vitamin C source.",
    documented_nutrients: { vitamin_c: "very high" },
    warnings: "Remove irritating seeds/hairs before use. Adult preparation required.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Used in wartime Britain as a vitamin C source.",
    cultural_notes: "Classic British wild food.",
    verification_status: "verified" as const
  },
  {
    slug: "oak",
    common_name: "Oak",
    scientific_name: "Quercus robur (English oak) and others",
    other_names: [],
    plant_family: "Fagaceae",
    native_region: ["Europe", "Northern Hemisphere species vary"],
    current_distribution: ["Temperate regions"],
    description: "Long-lived tree with lobed leaves and acorns.",
    growth_habit: "Tree",
    edible_parts: ["acorns (after leaching tannins — traditional processing)"],
    traditional_uses: "Acorns historically processed into flour in some cultures; timber, habitat.",
    documented_nutrients: {},
    warnings: "Raw acorns contain tannins and are not directly edible. Processing knowledge required. Never experiment without expert guidance.",
    toxic_parts: ["raw acorns (high tannin)"],
    allergens: [],
    historical_notes: "Keystone species of British and European woodlands; sacred in many cultures.",
    cultural_notes: "National tree associations; Tree Council character potential.",
    verification_status: "verified" as const
  },

  // ——— Globally familiar ———
  {
    slug: "apple",
    common_name: "Apple",
    scientific_name: "Malus domestica",
    other_names: [],
    plant_family: "Rosaceae",
    native_region: ["Central Asia (Kazakhstan region)"],
    current_distribution: ["Temperate worldwide"],
    description: "Familiar pome fruit with countless cultivars.",
    growth_habit: "Tree",
    edible_parts: ["fruit"],
    traditional_uses: "Eaten fresh, cooked, fermented (cider).",
    documented_nutrients: { fiber: "present", vitamin_c: "present" },
    warnings: "Seeds contain small amounts of cyanogenic compounds — do not eat large quantities of seeds.",
    toxic_parts: ["seeds (in quantity)"],
    allergens: ["oral allergy syndrome possible"],
    historical_notes: "Domesticated in Central Asia; spread along Silk Road and by Europeans worldwide.",
    cultural_notes: "One of the most culturally significant fruits in temperate zones.",
    verification_status: "verified" as const
  },
  {
    slug: "orange",
    common_name: "Orange",
    scientific_name: "Citrus × sinensis",
    other_names: ["Sweet orange"],
    plant_family: "Rutaceae",
    native_region: ["South China / Southeast Asia hybrid origin"],
    current_distribution: ["Subtropics and tropics"],
    description: "Sweet citrus fruit, major global crop.",
    growth_habit: "Tree",
    edible_parts: ["fruit segments", "juice"],
    traditional_uses: "Eaten fresh, juiced; historically valued for preventing scurvy.",
    documented_nutrients: { vitamin_c: "high", fiber: "present" },
    warnings: "None for normal consumption.",
    toxic_parts: [],
    allergens: ["citrus sensitivity possible"],
    historical_notes: "Hybrid citrus that spread via trade routes; crucial for sailors’ health (scurvy).",
    cultural_notes: "Global breakfast staple; sailors carried citrus for vitamin C.",
    verification_status: "verified" as const
  },
  {
    slug: "lemon",
    common_name: "Lemon",
    scientific_name: "Citrus limon",
    other_names: [],
    plant_family: "Rutaceae",
    native_region: ["Asia (hybrid origin)"],
    current_distribution: ["Subtropics"],
    description: "Sour yellow citrus used for flavour and acidity.",
    growth_habit: "Tree",
    edible_parts: ["juice", "zest", "segments"],
    traditional_uses: "Flavouring, drinks, preservation, traditional uses.",
    documented_nutrients: { vitamin_c: "high" },
    warnings: "None for normal culinary use.",
    toxic_parts: [],
    allergens: ["citrus sensitivity possible"],
    historical_notes: "Spread through Islamic world and into Europe; later global.",
    cultural_notes: "Essential kitchen citrus worldwide.",
    verification_status: "verified" as const
  },
  {
    slug: "carrot",
    common_name: "Carrot",
    scientific_name: "Daucus carota subsp. sativus",
    other_names: [],
    plant_family: "Apiaceae",
    native_region: ["Central Asia / Europe (wild ancestor)"],
    current_distribution: ["Worldwide"],
    description: "Orange (or purple, yellow, white) root vegetable.",
    growth_habit: "Biennial (grown as annual)",
    edible_parts: ["root", "leaves (in moderation)"],
    traditional_uses: "Eaten raw or cooked; historically many colours before orange became dominant.",
    documented_nutrients: { beta_carotene: "very high", fiber: "present" },
    warnings: "None for normal consumption.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Orange carrots were popularised in the Netherlands; wild carrot is Eurasian.",
    cultural_notes: "One of the most familiar vegetables for children.",
    verification_status: "verified" as const
  },
  {
    slug: "potato",
    common_name: "Potato",
    scientific_name: "Solanum tuberosum",
    other_names: [],
    plant_family: "Solanaceae",
    native_region: ["Andes (South America)"],
    current_distribution: ["Worldwide"],
    description: "Starchy tuber that became a global staple.",
    growth_habit: "Herbaceous perennial (grown as annual)",
    edible_parts: ["tuber (cooked)"],
    traditional_uses: "Boiled, roasted, fried, mashed — countless preparations.",
    documented_nutrients: { carbohydrates: "high", vitamin_c: "present", potassium: "present" },
    warnings: "Green parts and sprouts contain solanine — do not eat. Always cook potatoes.",
    toxic_parts: ["green skin", "sprouts", "leaves", "berries"],
    allergens: [],
    historical_notes: "Domesticated in the Andes; transformed European and global agriculture after the Columbian Exchange.",
    cultural_notes: "One of the world’s most important food crops.",
    verification_status: "verified" as const
  },
  {
    slug: "sweet-potato",
    common_name: "Sweet Potato",
    scientific_name: "Ipomoea batatas",
    other_names: ["Yam (incorrectly in some regions)"],
    plant_family: "Convolvulaceae",
    native_region: ["Central / South America"],
    current_distribution: ["Tropics and warm regions"],
    description: "Sweet starchy storage root; not a true yam.",
    growth_habit: "Trailing vine",
    edible_parts: ["root", "leaves (some varieties)"],
    traditional_uses: "Roasted, boiled, mashed, in desserts and stews.",
    documented_nutrients: { beta_carotene: "high (orange types)", fiber: "present", vitamin_c: "present" },
    warnings: "None for normal consumption of the root.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Ancient American domesticate; reached Polynesia and later the wider world.",
    cultural_notes: "Important in African, Caribbean, American and Pacific diets.",
    verification_status: "verified" as const
  },
  {
    slug: "rice",
    common_name: "Rice",
    scientific_name: "Oryza sativa (Asian) / Oryza glaberrima (African)",
    other_names: [],
    plant_family: "Poaceae",
    native_region: ["Asia (O. sativa)", "West Africa (O. glaberrima)"],
    current_distribution: ["Tropics and warm temperate"],
    description: "The world’s most important cereal for human calories.",
    growth_habit: "Annual grass (usually)",
    edible_parts: ["grain"],
    traditional_uses: "Boiled, steamed, porridge, fermented, countless dishes.",
    documented_nutrients: { carbohydrates: "high" },
    warnings: "None for normal consumption.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Two independent domestications: Asia and West Africa. Transformed civilisations.",
    cultural_notes: "Foundation of meals for billions of people.",
    verification_status: "verified" as const
  },
  {
    slug: "wheat",
    common_name: "Wheat",
    scientific_name: "Triticum spp.",
    other_names: [],
    plant_family: "Poaceae",
    native_region: ["Fertile Crescent"],
    current_distribution: ["Temperate worldwide"],
    description: "Primary bread cereal of temperate civilisations.",
    growth_habit: "Annual grass",
    edible_parts: ["grain"],
    traditional_uses: "Bread, pasta, couscous, porridge, beer.",
    documented_nutrients: { carbohydrates: "high", protein: "present (gluten)" },
    warnings: "Contains gluten — not suitable for people with coeliac disease.",
    toxic_parts: [],
    allergens: ["gluten / wheat allergy"],
    historical_notes: "Domesticated in the Fertile Crescent; enabled settled agriculture and cities.",
    cultural_notes: "Central to many European, Middle Eastern and global food cultures.",
    verification_status: "verified" as const
  },
  {
    slug: "sunflower",
    common_name: "Sunflower",
    scientific_name: "Helianthus annuus",
    other_names: [],
    plant_family: "Asteraceae",
    native_region: ["North America"],
    current_distribution: ["Worldwide"],
    description: "Tall flower with large seed head that follows the sun (young plants).",
    growth_habit: "Annual",
    edible_parts: ["seeds"],
    traditional_uses: "Seeds eaten or pressed for oil; ornamental.",
    documented_nutrients: { vitamin_e: "high", healthy_fats: "present", protein: "present" },
    warnings: "None for normal seed consumption.",
    toxic_parts: [],
    allergens: ["possible"],
    historical_notes: "Domesticated by Indigenous peoples of North America; now global oil crop.",
    cultural_notes: "Excellent for teaching patterns, maths and pollination.",
    verification_status: "verified" as const
  },
  {
    slug: "pumpkin",
    common_name: "Pumpkin",
    scientific_name: "Cucurbita pepo / maxima / moschata",
    other_names: ["Squash"],
    plant_family: "Cucurbitaceae",
    native_region: ["Americas"],
    current_distribution: ["Worldwide"],
    description: "Large winter squash with edible flesh and seeds.",
    growth_habit: "Trailing annual vine",
    edible_parts: ["flesh", "seeds", "flowers (some)"],
    traditional_uses: "Roasted, soups, pies, seeds roasted.",
    documented_nutrients: { vitamin_a: "high", fiber: "present" },
    warnings: "None for normal consumption.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "One of the ‘Three Sisters’ crops of many Indigenous American agricultures (with maize and beans).",
    cultural_notes: "Halloween and harvest symbol; excellent for seed maths.",
    verification_status: "verified" as const
  },
  {
    slug: "ginger",
    common_name: "Ginger",
    scientific_name: "Zingiber officinale",
    other_names: [],
    plant_family: "Zingiberaceae",
    native_region: ["Maritime Southeast Asia"],
    current_distribution: ["Tropics"],
    description: "Aromatic rhizome used as spice and in traditional preparations.",
    growth_habit: "Herbaceous perennial",
    edible_parts: ["rhizome"],
    traditional_uses: "Fresh, dried or powdered spice; teas; traditional herbal use in many cultures.",
    documented_nutrients: { gingerols: "present" },
    warnings: "Culinary amounts are widely used. Medicinal claims should be evidence-checked.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Ancient trade spice; reached Europe via long trade routes.",
    cultural_notes: "Essential in Asian, Caribbean and global cooking.",
    verification_status: "verified" as const
  },
  {
    slug: "turmeric",
    common_name: "Turmeric",
    scientific_name: "Curcuma longa",
    other_names: ["Haldi"],
    plant_family: "Zingiberaceae",
    native_region: ["South / Southeast Asia"],
    current_distribution: ["Tropics"],
    description: "Bright orange rhizome used as spice and colouring.",
    growth_habit: "Herbaceous perennial",
    edible_parts: ["rhizome"],
    traditional_uses: "Spice, colouring, traditional use in South Asian and other systems.",
    documented_nutrients: { curcuminoids: "present" },
    warnings: "Culinary use is widespread. Health claims require careful evidence evaluation.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Long history in South Asian cuisine and traditional practices.",
    cultural_notes: "Gives curry its colour; important in Caribbean and global kitchens too.",
    verification_status: "verified" as const
  },
  {
    slug: "baobab",
    common_name: "Baobab",
    scientific_name: "Adansonia digitata (African)",
    other_names: ["Upside-down tree"],
    plant_family: "Malvaceae",
    native_region: ["Africa"],
    current_distribution: ["African drylands", "some other Adansonia in Madagascar/Australia"],
    description: "Massive trunked tree that stores water; fruit is nutrient-dense.",
    growth_habit: "Tree",
    edible_parts: ["fruit pulp", "seeds (processed)"],
    traditional_uses: "Fruit powder in drinks and food; leaves and seeds used in traditional ways; tree is culturally sacred in many places.",
    documented_nutrients: { vitamin_c: "very high in pulp", fiber: "high", calcium: "present" },
    warnings: "Respect cultural significance. Source fruit powder from reputable suppliers.",
    toxic_parts: [],
    allergens: [],
    historical_notes: "Iconic African tree; fruit now globally traded as a superfood powder.",
    cultural_notes: "Perfect Tree Council elder character — ancient, wise, life-giving.",
    verification_status: "verified" as const
  }
];
