/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as FarmRouteImport } from './routes/farm'
import { Route as LanguagesRouteImport } from './routes/languages'
import { Route as MapRouteImport } from './routes/map'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as PressRouteImport } from './routes/press'
import { Route as SchoolsRouteImport } from './routes/schools'
import { Route as SearchRouteImport } from './routes/search'
import { Route as StartRouteImport } from './routes/start'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as CrewIndexRouteImport } from './routes/crew/index'
import { Route as CrewSlugRouteImport } from './routes/crew/$slug'
import { Route as PlantsIndexRouteImport } from './routes/plants/index'
import { Route as PlantsSlugRouteImport } from './routes/plants/$slug'
import { Route as SingIndexRouteImport } from './routes/sing/index'
import { Route as SingSlugRouteImport } from './routes/sing/$slug'
import { Route as WatchIndexRouteImport } from './routes/watch/index'
import { Route as WatchSlugRouteImport } from './routes/watch/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const FarmRoute = FarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => rootRouteImport,
} as any)
const LanguagesRoute = LanguagesRouteImport.update({
  id: '/languages',
  path: '/languages',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolsRoute = SchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewIndexRoute = CrewIndexRouteImport.update({
  id: '/crew/',
  path: '/crew/',
  getParentRoute: () => rootRouteImport,
} as any)
const CrewSlugRoute = CrewSlugRouteImport.update({
  id: '/crew/$slug',
  path: '/crew/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsIndexRoute = PlantsIndexRouteImport.update({
  id: '/plants/',
  path: '/plants/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsSlugRoute = PlantsSlugRouteImport.update({
  id: '/plants/$slug',
  path: '/plants/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SingIndexRoute = SingIndexRouteImport.update({
  id: '/sing/',
  path: '/sing/',
  getParentRoute: () => rootRouteImport,
} as any)
const SingSlugRoute = SingSlugRouteImport.update({
  id: '/sing/$slug',
  path: '/sing/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIndexRoute = WatchIndexRouteImport.update({
  id: '/watch/',
  path: '/watch/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchSlugRoute = WatchSlugRouteImport.update({
  id: '/watch/$slug',
  path: '/watch/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/family': typeof FamilyRoute
  '/farm': typeof FarmRoute
  '/languages': typeof LanguagesRoute
  '/map': typeof MapRoute
  '/parents': typeof ParentsRoute
  '/press': typeof PressRoute
  '/schools': typeof SchoolsRoute
  '/search': typeof SearchRoute
  '/start': typeof StartRoute
  '/studio': typeof StudioRoute
  '/crew/$slug': typeof CrewSlugRoute
  '/plants/$slug': typeof PlantsSlugRoute
  '/sing/$slug': typeof SingSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/crew/': typeof CrewIndexRoute
  '/plants/': typeof PlantsIndexRoute
  '/sing/': typeof SingIndexRoute
  '/watch/': typeof WatchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/family': typeof FamilyRoute
  '/farm': typeof FarmRoute
  '/languages': typeof LanguagesRoute
  '/map': typeof MapRoute
  '/parents': typeof ParentsRoute
  '/press': typeof PressRoute
  '/schools': typeof SchoolsRoute
  '/search': typeof SearchRoute
  '/start': typeof StartRoute
  '/studio': typeof StudioRoute
  '/crew/$slug': typeof CrewSlugRoute
  '/plants/$slug': typeof PlantsSlugRoute
  '/sing/$slug': typeof SingSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/crew': typeof CrewIndexRoute
  '/plants': typeof PlantsIndexRoute
  '/sing': typeof SingIndexRoute
  '/watch': typeof WatchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/family': typeof FamilyRoute
  '/farm': typeof FarmRoute
  '/languages': typeof LanguagesRoute
  '/map': typeof MapRoute
  '/parents': typeof ParentsRoute
  '/press': typeof PressRoute
  '/schools': typeof SchoolsRoute
  '/search': typeof SearchRoute
  '/start': typeof StartRoute
  '/studio': typeof StudioRoute
  '/crew/$slug': typeof CrewSlugRoute
  '/plants/$slug': typeof PlantsSlugRoute
  '/sing/$slug': typeof SingSlugRoute
  '/watch/$slug': typeof WatchSlugRoute
  '/crew/': typeof CrewIndexRoute
  '/plants/': typeof PlantsIndexRoute
  '/sing/': typeof SingIndexRoute
  '/watch/': typeof WatchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/family'
    | '/farm'
    | '/languages'
    | '/map'
    | '/parents'
    | '/press'
    | '/schools'
    | '/search'
    | '/start'
    | '/studio'
    | '/crew/$slug'
    | '/plants/$slug'
    | '/sing/$slug'
    | '/watch/$slug'
    | '/crew/'
    | '/plants/'
    | '/sing/'
    | '/watch/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/family'
    | '/farm'
    | '/languages'
    | '/map'
    | '/parents'
    | '/press'
    | '/schools'
    | '/search'
    | '/start'
    | '/studio'
    | '/crew/$slug'
    | '/plants/$slug'
    | '/sing/$slug'
    | '/watch/$slug'
    | '/crew'
    | '/plants'
    | '/sing'
    | '/watch'
  id:
    | '__root__'
    | '/'
    | '/family'
    | '/farm'
    | '/languages'
    | '/map'
    | '/parents'
    | '/press'
    | '/schools'
    | '/search'
    | '/start'
    | '/studio'
    | '/crew/$slug'
    | '/plants/$slug'
    | '/sing/$slug'
    | '/watch/$slug'
    | '/crew/'
    | '/plants/'
    | '/sing/'
    | '/watch/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FamilyRoute: typeof FamilyRoute
  FarmRoute: typeof FarmRoute
  LanguagesRoute: typeof LanguagesRoute
  MapRoute: typeof MapRoute
  ParentsRoute: typeof ParentsRoute
  PressRoute: typeof PressRoute
  SchoolsRoute: typeof SchoolsRoute
  SearchRoute: typeof SearchRoute
  StartRoute: typeof StartRoute
  StudioRoute: typeof StudioRoute
  CrewSlugRoute: typeof CrewSlugRoute
  PlantsSlugRoute: typeof PlantsSlugRoute
  SingSlugRoute: typeof SingSlugRoute
  WatchSlugRoute: typeof WatchSlugRoute
  CrewIndexRoute: typeof CrewIndexRoute
  PlantsIndexRoute: typeof PlantsIndexRoute
  SingIndexRoute: typeof SingIndexRoute
  WatchIndexRoute: typeof WatchIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/farm': {
      id: '/farm'
      path: '/farm'
      fullPath: '/farm'
      preLoaderRoute: typeof FarmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/languages': {
      id: '/languages'
      path: '/languages'
      fullPath: '/languages'
      preLoaderRoute: typeof LanguagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schools': {
      id: '/schools'
      path: '/schools'
      fullPath: '/schools'
      preLoaderRoute: typeof SchoolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/': {
      id: '/crew/'
      path: '/crew'
      fullPath: '/crew/'
      preLoaderRoute: typeof CrewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crew/$slug': {
      id: '/crew/$slug'
      path: '/crew/$slug'
      fullPath: '/crew/$slug'
      preLoaderRoute: typeof CrewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/': {
      id: '/plants/'
      path: '/plants'
      fullPath: '/plants/'
      preLoaderRoute: typeof PlantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/$slug': {
      id: '/plants/$slug'
      path: '/plants/$slug'
      fullPath: '/plants/$slug'
      preLoaderRoute: typeof PlantsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sing/': {
      id: '/sing/'
      path: '/sing'
      fullPath: '/sing/'
      preLoaderRoute: typeof SingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sing/$slug': {
      id: '/sing/$slug'
      path: '/sing/$slug'
      fullPath: '/sing/$slug'
      preLoaderRoute: typeof SingSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/': {
      id: '/watch/'
      path: '/watch'
      fullPath: '/watch/'
      preLoaderRoute: typeof WatchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$slug': {
      id: '/watch/$slug'
      path: '/watch/$slug'
      fullPath: '/watch/$slug'
      preLoaderRoute: typeof WatchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FamilyRoute: FamilyRoute,
  FarmRoute: FarmRoute,
  LanguagesRoute: LanguagesRoute,
  MapRoute: MapRoute,
  ParentsRoute: ParentsRoute,
  PressRoute: PressRoute,
  SchoolsRoute: SchoolsRoute,
  SearchRoute: SearchRoute,
  StartRoute: StartRoute,
  StudioRoute: StudioRoute,
  CrewSlugRoute: CrewSlugRoute,
  PlantsSlugRoute: PlantsSlugRoute,
  SingSlugRoute: SingSlugRoute,
  WatchSlugRoute: WatchSlugRoute,
  CrewIndexRoute: CrewIndexRoute,
  PlantsIndexRoute: PlantsIndexRoute,
  SingIndexRoute: SingIndexRoute,
  WatchIndexRoute: WatchIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
